Main["Cover Arragments"] = [
	"A Sunny Day Is Watching Over You - Nekojishi",
	"Addict - Hazbin Hotel",
	"An Enigmatic Encounter - Undertale (Last breath) ver. 2",
	"An Enigmatic Encounter - Undertale (Last breath)",
	"Anarchy Rainbow - Splatoon 3 [Choir interpretation]",
	"Anarchy Rainbow - Splatoon 3 [Instrumental]",
	"Anarchy Rainbow - Splatoon 3 Ver. 2 [Choir interpretation]",
	"Anarchy Rainbow - Splatoon 3 Ver. 2 [Instrumental]",
	"Anarchy Rainbow - Splatoon 3 Ver. 2",
	"Anarchy Rainbow - Splatoon 3",
	"ANIMAL IN ME  - Solence",
	"ANIMAL IN ME - Solence Ver. 2",
	"Area Zero - Pokémon Scarlet & Violet Ver. 2",
	"Area Zero - Pokémon Scarlet & Violet",
	"Area Zero Wild Battle - Pokémon Scarlet & Violet",
	"Ashfaghma ot bantiem (Bergentrückung Arragment) - Undertale",
	"Attack of the Killer Queen Remix (Attack of the Killer Queen Arragment) - Deltarune",
	"Avast Your Ass - Kitsune²",
	"Backbone [Phase 3] - Disbelief Papyrus Ver. 2",
	"Backbone [Phase 3] - Disbelief Papyrus",
	"Bad Apple - Touhou project ",
	"Bad Apple - Touhou project ver. 2",
	"Balrog's Theme - Cave Story",
	"Battle (destruction) - Shin Megami Tensei V",
	"Battle (guardian) - TLOZ BOTW",
	"BATTLE AGAINST THE WORLD - Deltarune [Chapter Rewritten]",
	"BIG BANG - Deltarune [Chapter Rewritten]",
	"BIG BANG (Updated Version) - Deltarune [Chapter Rewritten]",
	"BITE [FERNAN MIX] [No FNF Vocals]",
	"BITE [FERNAN MIX]",
	"Bloody Tears - Castelvania",
	"Blooming revolver - Deltarune UST",
	"Blooming revolver (Orchestral arragment) - Deltarune UST",
	"Bonnqueet grand queen (Queen's themes Arragments) - Deltarune",
	"Boogieman [No FNF Vocals]",
	"Boogieman",
	"Bowser Road - MS64",
	"Calamari Inkantation 3MIX - Splatoon 3 [instrumental]",
	"Calamari Inkantation 3MIX - Splatoon 3",
	"Cascade - HomeStuck Vol 8",
	"Champion Battle - Pokemon Insurgence",
	"Clock Town Day 1 - TLOZ MM",
	"Coconut - Jayfoo [Doodley Soundtrack, Vol. 1]",
	"Colgera - TLOZ TOTK",
	"Cool, cool mountain - SM64",
	"Count What You Have Now - Mariya Takeuchi",
	"CP Violation - Half Life 2",
	"CREATIVE FREEDOM - U.Z Inu",
	"Credits song for my death - vivivivivi Ver. 2",
	"Credits song for my death - vivivivivi",
	"Daisy bell (Bicycle build for two) - Harry Dacre",
	"Darkest Lord - Miitopia ver. 2",
	"Darkest Lord - Miitopia",
	"Darkness Falls & Faint Courage - Deltarune",
	"Daycare - FNAF SB",
	"Deal Gone Wrong (violin fading) - Deltarune",
	"Deal Gone Wrong choir catastrhopy (Deal gone wrong Arragment) - Deltarune",
	"Deerclops (The E.F.S. of Winter) - Terraria",
	"Delete this tweet - Trash cans - Kevin Temmer",
	"Demon castle dracula - Super Castlevania IV",
	"Dialga's Fight to the Finish! - Pokemon Mystery Dungeon Explorers of Time Darkness",
	"Dire Dire Docks - MS64",
	"Dire Dire Docks - SM64 Ver. 2",
	"Discord - Eurobeat Ver 2",
	"Discord - Eurobeat",
	"Dj music man - FNAF SB",
	"Don't Ever Forget - Pokemon Mystery Dungeon (Explorers of Sky)",
	"Dracula's Keep - Super Castlevania IV",
	"Dracula's theme - Castelvania 4",
	"Driftveil city - Pokemon Black & White",
	"Duel of the Fates - StarWars",
	"Echo [Gumi Ingles] - Crusher-P",
	"Ei Mori Roujke - Nonesuch (Bulgarian female choir)",
	"Even in Death - Homestuck Vol 7",
	"Final chance [Phase 4] - Disbelief Papyrus",
	"Finding another medium (another medium Arragment) - Undertale",
	"Flowering Night - Touhou Project",
	"Forgotten One Nyx - Pokémon Insurgence",
	"From the Shadows - Shovel Knight",
	"Gang-Plank Galleon - Super Smash Bros. Ultimate",
	"Gerudo Valley - TLOZ OOT ver. 2",
	"Gerudo Valley - TLOZ OOT",
	"Giants - Skylander Giants",
	"GIGA プリン - Deltarune [The Other Puppet] Ver. 2",
	"GIGA プリン - Deltarune [The Other Puppet]",
	"God Save The Queen - UK",
	"Goodbye To A World - Poter Robinson",
	"Gourmet Race - Kirby Super star",
	"GRAND ILLUSsSIONSsS - Deltarune Chapter 3 UST",
	"Grass Skirt Chase - SpongeBob SquarePants",
	"Happy Birthday",
	"HARD DRIVE - Griffinilla [Instrumental]",
	"HARD DRIVE - Griffinilla",
	"Heartaches - Al-Bowlly",
	"Heaven Says - Deltarune UST Ver. 2",
	"Heaven Says - Deltarune UST",
	"Hell March 3 - Red Alert 3",
	"Hijo de la luna - Mecano ver. 2",
	"Hijo de la luna - Mecano",
	"His World (Sonic's Theme) - Sonic the Hedgehog [Instrumental]",
	"His World (Sonic's Theme) - Sonic the Hedgehog",
	"Horse racing - Chen jun ver.2 ",
	"Horse racing - Chen jun",
	"I CAN Y̴̘͘O̶U ̴̛̲̓C̶̭͒̿Ḁ̷̖̒N̵̻̽̊ - Deltarune [Chapter Rewritten]",
	"Idol - YOASOBI Ver.2 [Instrumental]",
	"Idol - YOASOBI Ver.2",
	"Idol - YOASOBI",
	"Inferno - Fire Force",
	"Interstellar Retribution [Phase 1] - Disbelief Papyrus Ver. 2",
	"Interstellar Retribution [Phase 1] - Disbelief Papyrus",
	"It's been so long - The living tombstone [FNAF]",
	"I've Had Enough of You - Billie Bust Up [Instrumental]",
	"I've Had Enough of You - Billie Bust Up",
	"Jedi Temple March - StarWars",
	"Jinora's light (Lotus Despair) - Legend of Korra",
	"Just look my way - Helluva Boss [Instrumental]",
	"Just look my way - Helluva Boss",
	"Just the two of us - Grover Washington, Jr. (feat. Bill Withers)",
	"Kaboomberg - ToonTown Ver. 2",
	"Kaboomberg - ToonTown",
	"Kalos Region - Pokemon X & Y",
	"Killer Kueen Bites The Dust - Deltarune [Chapter Rewritten]",
	"KING (Gumi) - Kanaria [Instrumental]",
	"KING (Gumi) - Kanaria",
	"Kokiri Forest - TLOZ OOT",
	"La Gozadera - Gente de Zona (ft. Marc Anthony) Instrumental",
	"La Gozadera - Gente de Zona (ft. Marc Anthony)",
	"Lagtrain - 稲葉曇 [Instrumental]",
	"Lagtrain - 稲葉曇",
	"Laugh Track - Deltarune Chapter 3 UST ver. 2",
	"Laugh Track - Deltarune Chapter 3 UST",
	"Lavender Town - Pokemon Red, Blue, Green & Yellow",
	"Law - Shin Megami Tensei III Nocturne",
	"Left Unchecked [No FNF Vocals]",
	"Left Unchecked",
	"Library Piano - Luigi's Mansion Dark Moon",
	"Littleroot Town - Pokemon Ruby & Sapphire & Emerald",
	"Lorule Castle - TLOZ ALBW ver. 2",
	"Lorule Castle - TLOZ ALBW",
	"Lost Woods - TLOZ OOT",
	"Lost, forgotten, down Friend (Lost girl - arragment) - Deltarune",
	"Louane - JOUR 1",
	"Low Kromer (Big Shot Arragment) - Deltarune",
	"Main theme - Bad Piggies ver. 2",
	"Main theme - Bad Piggies",
	"Main theme - El Vendedor de Humo - The Smoke Seller (Recreation & Cover)",
	"Main theme - Papers Please",
	"Main Theme - Skylanders SuperChargers",
	"Main Theme - Skylanders The Swap Force",
	"Main Theme - Terminator Genisys",
	"Main theme - Wii Sports",
	"Marble Machine - Wintergatan",
	"Marx's Theme - Kirby Super star",
	"Megalo Clamour - Kibo",
	"Megalo Strike Back - Earthbound Halloween hack",
	"Megalo strikes back [Phase 2] - Disbelief Papyrus Ver. 2",
	"Megalo strikes back [Phase 2] - Disbelief Papyrus",
	"Merry Go Round Life - howl's castle ver. 2",
	"Merry Go Round Life - howl's castle",
	"Merry Go Round Super - SM64",
	"Metatron - Shin Megami Tensei III Nocturne",
	"Missa langosta - Missa sinfonia",
	"MonoChrome [No FNF Vocals]",
	"MonoChrome",
	"MTC - S3RL",
	"Never gonna give you up - Rick Astley",
	"Nigh of nights - Touhou project",
	"Nightmare Knight - Cucumber quest (Toby fox) Ver. 2 ",
	"Nightmare Knight - Cucumber quest (Toby fox)",
	"No More Deals - Undetale (No More Deals) ver. 2",
	"No More Deals - Undetale (No More Deals)",
	"No se habla de bruno - Encanto",
	"OFFICIAL WAY - Deltarune Chapter 3 UST",
	"Open up your eyes - My little pony (The Movie) [Instrumental]",
	"Open up your eyes - My little pony (The Movie)",
	"Opposing Bloodlines - Castlevania 64",
	"PEACHES - [Jack Black - BOWSER] The super mario movie [inst]",
	"PEACHES - [Jack Black - BOWSER] The super mario movie",
	"Perseverance - Gris",
	"Phantasm [No FNF Vocals]",
	"Phantasm",
	"Piranha Plants on Parade - Super Mario Wonder",
	"Pirate seas - PVZ2",
	"Pirates sea [unused track] - PVZ2",
	"PokeWalker - Pokemon Heart Gold & Soul Silver",
	"PS5 - MrMoMMusic (feat. Alan Walker)",
	"Push Your Limits - Brian Michael Hinds [Instrumental]",
	"Push Your Limits - Brian Michael Hinds",
	"Relight [Gaster's theme] - Underverse",
	"Road Less Taken Real - Persona Q2",
	"Rolling Down the Street - Fearofdark",
	"Rolling Girl - Wowaka ver.2",
	"Rolling Girl - Wowaka",
	"Savior of the Waking World - Homestuck Vol 5",
	"Schoolhouse Trouble! - Baldi's Basics Classic Remastered",
	"Shala's Theme - Dream Devourer [Anti-Remix]",
	"Sidon's theme - TLOZ BOTW",
	"Silly Billy [Inst]",
	"Silly Billy [No FNF Vocals]",
	"Silly Billy",
	"Sis Puella Magica - Puella Magi Madoka Magica",
	"Slider - SM64",
	"Somebody else - Kevin Temmer",
	"Song of Storms - TLOZ OOF",
	"Spooky scary skeletons - Andrew Gold [Happy halloween]",
	"Spooky scary skeletons - Andrew Gold",
	"Spyro's Adventure - Skylanders",
	"Staff Rol - SM64",
	"Stay With Me - Miki Matsubara [instrumental]",
	"Stay With Me - Miki Matsubara",
	"Stolas Sings - Helluva Boss",
	"Stolas Sings [Dark] - Helluva Boss",
	"Stolas Singss - Helluva Boss [Instrumental]",
	"Stolas Singss [Dark] - Helluva Boss [Instrumental]",
	"Strike the earth - Shovel Knight",
	"Super Idol - 105",
	"Sweden Minecraft",
	"The Boiler - ToonTown Rewritten",
	"The Crisis of Red and Green - Mario & Luigi [Partners in Time]",
	"The Grand Finale - Mario & Luigi Bowser inside story",
	"The Great Sage's - Miitopia",
	"The Killer Spin - Deltarune UST",
	"The Killer Spin (Orchestral arragment) - Deltarune UST",
	"The Minister (Vision Crew's) - Deltarune Chapter 5 UST",
	"The Nowhere King - Centaurworld [Instrumental]",
	"The Nowhere King - Centaurworld",
	"The Opening of Every Animated Film - Kevin Temmer Tunes",
	"The Piano Duet - Corpse Bride",
	"The slaughter continues - Undertale (Last breath)",
	"The Toybox - Stupendium",
	"The World Revolving Another remix (The World Revolving - Arragment) - Deltarune",
	"Tower Battle - Pokemon shield & Sword",
	"Triple Trouble [No FNF Vocals] Ver. 2",
	"Triple Trouble [No FNF Vocals]",
	"Triple Trouble Ver. 2",
	"Triple Trouble",
	"U.N. Owen was her - Touhou Project",
	"Ultimate Bowser - MS64",
	"Upward Movement (Dave Own) - HomeStuck Vol 2",
	"Vitality - Helltaker",
	"Wart - Super Mario Bros 2 [Extended]",
	"Wart - Super Mario Bros 2",
	"We are - One Pice",
	"We Dont Talk About Bruno - Encanto",
	"We Dont Talk About Bruno No Se Habla De Bruno - Encanto [Instrumental]",
	"Wet Hands - Minecraft",
	"Wielder Volo Battle - Pokemon Arceus ver. 2",
	"Wielder Volo Battle - Pokemon Arceus",
	"wild battle - Pokemon Ruby & Sapphire & Emerald",
	"Yap Squad [Inst]",
	"Yap Squad [No FNF Vocals]",
	"Yap Squad",
	"Yo buddy - Deltarune [The Other Puppet]",
	"You smell of death flowers - Vslush",
	"You Will Be Ok - Helluva Boss",
	"You'er Truly A Real Boy! - Deltarune [fan UST]",
	"Your Contract Has Expired - A Hat In Time Ver. 2",
	"Your Contract Has Expired - A Hat In Time",
	"Your Contract Has Expired {hard} - A Hat In Time Ver. 2",
	"Your Contract Has Expired {hard} - A Hat In Time",
	"YOUR LAST GIFT - Local H00ligan",
	"Zero Two - Kirby 64 (The Crystal Shards)",
	"柴又 (Shibamata) - Dot nigou"
];