Main["Cover Albums"]={};
Main["Cover Albums"]["(OLD) Deltarune Chapter 1"] = [
	"-.Char Joined",
	"-.Man",
	"-.Thrash Rating",
	"01.ANOTHER HIM",
	"02.Beginning",
	"03.School",
	"04.Susie",
	"05.The Door",
	"06.Cliffs",
	"07.The Chase",
	"08.The Legend",
	"09.Lancer ver. 2",
	"09.Lancer",
	"10.Rude buster",
	"11.Empty Town",
	"13.Field of Hopes and Dreams ver. 2",
	"13.Field of Hopes and Dreams",
	"14.Fanfare (from Rose of Winter) short",
	"14.FanFare (from Rose of Winter)",
	"15.Lantern",
	"16.I'm very bad",
	"17.Chekers Dance",
	"18.Quiet Autumn",
	"19.Scarlet Forest",
	"20.Thrash Machine",
	"21.VS. Lancer",
	"22.Basement",
	"23.Imminent Death",
	"24.VS. Susie",
	"25.Card Castle",
	"26.Rouxls Kaard-Ruruskado",
	"27.April 2012",
	"28.Hip shop",
	"29.Gallery",
	"30.Chaos King ver. 2",
	"30.Chaos King",
	"31.Darkness Falls",
	"32.The Circus",
	"33.The World Revolving ver. 2",
	"33.The World Revolving",
	"34.Friendship",
	"35.THE HOLY",
	"36.Your Power",
	"37.A Town Called Hometown",
	"38.You Can Always Come Home",
	"39.Don't Forget",
	"40.Before the Story -482005294-",
	"40.Before the Story",
	"42.sans."
];
Main["Cover Albums"]["(OLD) Deltarune Chapter 2"] = [
	"-.A-pplause for Berdly",
	"-.Berdly Battle (Really Tense Heartbeat Momento Version)",
	"-.Cyber Battle",
	"-.Cybercity (Alt)",
	"-.D.ogg ",
	"01.Faint Glow",
	"02.Girl Next Door",
	"03.My Castle Town Ver. 2",
	"03.My Castle Town",
	"05.Queen Ver. 2",
	"05.Queen Ver. 3",
	"05.Queen",
	"06.A Cybers World Ver. 2",
	"06.A Cybers World",
	"07.A Simple Diversion ver. 2",
	"07.A Simple Diversion",
	"08.Almost To The Guys! Ver. 2",
	"08.Almost To The Guys!",
	"10.When I Get Mad I Dance Like This",
	"11.Toby Fox & Lena Raine - Cyber Battle",
	"12.When I Get Happy I Dance Like This",
	"13.Sound Studio",
	"14.Berdly",
	"15.Smart Race ver. 2",
	"15.Smart Race",
	"16.Faint Courage (Game Over) Ver. 2",
	"16.Faint Courage (Game Over) Ver. 3",
	"16.Faint Courage (Game Over)",
	"16.Faint Courage (Game Over)B side",
	"17.WELCOME TO THE CITY",
	"18.Mini Studio",
	"19.Holyday Studio",
	"20.Cool Mixtape",
	"21.HEY EVERY!",
	"22.Spamtom",
	"23.NOW'S YOUR CHANCE TO BE A",
	"24.Elegant Entrance",
	"25.Bluebird of Misfortune PIANO & VIOLIN",
	"25.Bluebird of Misfortune",
	"26.Pandora Palace Ver. 2",
	"26.Pandora Palace",
	"27.KEYGEN",
	"28.Acid Tunnel of Love",
	"29.It's Pronounced ¡Rules! ver. 2",
	"29.It's Pronounced ¡Rules!",
	"30.Lost Girl",
	"31.Ferris Wheel",
	"32.Toby Fox & Lena Raine & Marcy Nabors - Attack of the Killer Queen",
	"33.Giga Size",
	"34.Powers Combined",
	"35.Knock You Down",
	"36.The Dark Truth Ver. 2",
	"36.The Dark Truth",
	"37.Digital Roots",
	"38.Deal Gone Wrong ver. 2",
	"38.Deal Gone Wrong",
	"39.Big Shot ver. 2",
	"39.Big Shot ver. 3",
	"39.Big Shot",
	"40.A Real Boy!",
	"41.Dialtone",
	"42.sans.",
	"43.Napsta Alarm",
	"45.Until next time ver. 2",
	"45.Until next time"
];
Main["Cover Albums"]["(OLD) FNF Vs. Retrospecter"] = [
	"Acidiron [No FNF Vocals]",
	"Acidiron",
	"Fuzzy Feeling [No FNF Vocals]",
	"Fuzzy Feeling",
	"HeartMelter [no fnf voice]",
	"HeartMelter",
	"Overtime [no fnf voice]",
	"Overtime",
	"Preppy [no fnf voice]",
	"Preppy",
	"Preseason [no fnf voice]",
	"Preseason",
	"Retro [no fnf voice]",
	"Retro",
	"Satisfracture [no fnf voice]",
	"Satisfracture",
	"Sigma [no fnf voice]",
	"Sigma",
	"Spectral [no fnf voice]",
	"Spectral"
];
Main["Cover Albums"]["(OLD) Undertale"] = [
	"-.Absolutely Overfamiliar Shrine",
	"-.Before the Story -482005294-",
	"-.Before the Story",
	"-.Dance of dog",
	"-.Dog casino",
	"-.King Description",
	"-.Mad Mew Mew",
	"-.Mysterious Shrine",
	"+.mus_st_him",
	"001.Once Upon a Time",
	"002.Start Menu",
	"003.Your Best Friend",
	"004.Fallen Down Ver. 2",
	"004.Fallen Down",
	"005.Ruins Ver. 2",
	"005.Ruins",
	"006.Uwa!! So Temperate",
	"007.Anticipation",
	"008.Unnecessary Tension",
	"009.Enemy Approaching",
	"010.Ghost Fight",
	"011.Determination Ver. 2",
	"011.Determination",
	"012.Home",
	"013.Home (Music Box)",
	"014.Heartache Ver. 2",
	"014.Heartache",
	"015.sans.",
	"016.Nye heh heh! Ver. 2",
	"016.Nye heh heh!",
	"017.Snowy",
	"018.Uwa So Holiday",
	"020.Mysterious Place",
	"021.Dog Song",
	"022.Snowdin Town",
	"023.Shop Ver. 2",
	"023.Shop",
	"024.Bonetrousle Ver. 2",
	"024.Bonetrousle",
	"025.Dating Start",
	"026.Dating Tense!",
	"027.Dating Fight!",
	"028.Premonition",
	"029.Danger Mystery",
	"030.Undyne",
	"031.Waterfall",
	"032.Run!",
	"033.Quiet Water",
	"034.Memory",
	"035.Bird That Carries You Over A Disproportionately Small Gap ver. 2",
	"035.Bird That Carries You Over A Disproportionately Small Gap",
	"036.Dummy!",
	"037.Pathetic House",
	"038.Spooktune",
	"039.Spookwave",
	"040.Ghouliday",
	"041.Chill",
	"042.Thundersnail",
	"043.Temmie Village ver. 2",
	"043.Temmie Village",
	"044.Tem Shop",
	"045.NGAHHH!!",
	"046.Spear of Justice",
	"047.Ooo",
	"048.Alphys",
	"049.It's Showtime",
	"050.Another Medium ver. 2",
	"050.Another Medium",
	"051.Metal Crusher",
	"052.Uwa!! So HEATS!!",
	"053.Hotel Ver. 2",
	"053.Hotel",
	"054.Stronger Monsters",
	"055.Can You Really Call This A Hotel I Didn't Recieve A Mint On My Pillow Or Anything",
	"056.Confession",
	"057.Live Report",
	"058.Death Report ver.2",
	"058.Death Report",
	"059.Spider Dance",
	"060.Wrong Enemy",
	"061.Oh! One True Love",
	"062.Oh! Dungeon",
	"063.It's Raining Somewhere Else",
	"064.CORE Approach",
	"065.CORE",
	"066.Last Episode",
	"067.Oh My",
	"068.Death by Glamour ver. 2",
	"068.Death by Glamour",
	"069.For the Fans",
	"071.Undertale ver. 2",
	"071.Undertale",
	"072.Song That Might Play When You Fight Sans",
	"074.Small Shock",
	"076.Bergentrückung Ver. 2",
	"076.Bergentrückung",
	"077.ASGORE ver. 2",
	"077.ASGORE",
	"078.You Idiot",
	"079.Your Best Nightmare ver. 2",
	"079.Your Best Nightmare",
	"080.Finale",
	"081.An Ending",
	"082.She's Playing Piano",
	"083.Here We Are",
	"084.Amalgam ver. 2",
	"084.Amalgam",
	"085.Fallen Down (Reprise) ver. 2",
	"085.Fallen Down (Reprise)",
	"086.Don't Give Up",
	"087.Hopes and Dreams ver. 2",
	"087.Hopes and Dreams",
	"088.Burn in Despair",
	"089.SAVE the WORLD Ver. 2",
	"089.SAVE the WORLD",
	"090.His Theme",
	"092.Reunited ver. 2",
	"092.Reunited",
	"093.Start Menu (full)",
	"094.Respite",
	"095.Bring It In Guys Ver. 2",
	"095.Bring It In Guys",
	"096.Last Goodbye Ver. 2",
	"096.Last Goodbye",
	"097.But the Earth Refused to Die ver. 2",
	"097.But the Earth Refused to Die",
	"098.Battle Against a True Hero Ver. 2",
	"098.Battle Against a True Hero Ver. 3",
	"098.Battle Against a True Hero",
	"099.Power of NEO",
	"100.MEGALOVANIA Ver. 2",
	"100.MEGALOVANIA",
	"101.Good Night"
];
Main["Cover Albums"]["Dungeons of Aether"] = [
	"007.First Quarry (Area 1)",
	"008.Ground Breakers (Battle 1)"
];
Main["Cover Albums"]["FNF Smoke 'Em Out Struggle"] = [
	"Fading",
	"Headache",
	"Nerves",
	"Release",
];
Main["Cover Albums"]["FNF Vs. witthy"] = [
	"Ballistic",
	"Ballistic[No FNF Vocals]",
	"Lo-Fight [No FNF Vocals]",
	"Lo-Fight",
	"Low Rise [No FNF Vocals]",
	"Low Rise",
	"Overhead",
	"Underground"
];
Main["Cover Albums"]["Undertale"] = [
	"-.Absolutely Overfamiliar Shrine",
	"-.Before the Story",
	"-.Dance of dog",
	"-.Dog casino",
	"-.King Description",
	"-.Mad Mew Mew",
	"-.Mysterious Shrine",
	"-.Sigh of Dog",
	"-.Star",
	"-.The Wrong Number Song",
	"-.Toby Room",
	"001.Once Upon a Time",
	"002.Start Menu",
	"003.Your Best Friend",
	"004.Fallen Down",
	"005.Ruins",
	"006.Uwa!! So Temperate",
	"007.Anticipation",
	"008.Unnecessary Tension",
	"009.Enemy Approaching",
	"010.Ghost Fight",
	"011.Determination",
	"012.Home",
	"013.Home (Music Box)",
	"014.Heartache",
	"015.sans.",
	"016.Nye heh heh!",
	"017.Snowy",
	"018.Uwa So Holiday",
	"019.Dogbass",
	"020.Mysterious Place",
	"021.Dog Song",
	"022.Snowdin Town",
	"023.Shop",
	"024.Bonetrousle",
	"025.Dating Start",
	"026.Dating Tense!",
	"027.Dating Fight!",
	"028.Premonition",
	"029.Danger Mystery",
	"030.Undyne",
	"031.Waterfall",
	"032.Run!",
	"033.Quiet Water",
	"034.Memory",
	"035.Bird That Carries You Over A Disproportionately Small Gap",
	"036.Dummy!",
	"037.Pathetic House",
	"038.Spooktune",
	"039.Spookwave",
	"040.Ghouliday",
	"041.Chill",
	"042.Thundersnail",
	"043.Temmie Village",
	"044.Tem Shop",
	"045.NGAHHH!!",
	"046.Spear of Justice",
	"047.Ooo",
	"048.Alphys",
	"049.It's Showtime",
	"050.Metal Crusher",
	"051.Another Medium",
	"052.Uwa!! So HEATS!!",
	"053.Stronger Monsters",
	"054.Hotel",
	"055.Can You Really Call This A Hotel I Didn't Receive A Mint On My Pillow Or Anything",
	"056.Confession",
	"057.Live Report",
	"058.Death Report",
	"059.Spider Dance",
	"060.Wrong Enemy",
	"061.Oh! One True Love",
	"062.Oh! Dungeon",
	"063.It's Raining Somewhere Else",
	"064.CORE Approach",
	"065.CORE",
	"066.Last Episode",
	"067.Oh My...",
	"068.Death by Glamour",
	"069.For the Fans",
	"071.Undertale",
	"072.Song That Might Play When You Fight Sans",
	"074.Small Shock",
	"076.Bergentrückung",
	"077.ASGORE",
	"078.You Idiot",
	"079.Your Best Nightmare",
	"080.Finale",
	"081.An Ending",
	"082.She's Playing Piano",
	"083.Here We Are",
	"084.Amalgam",
	"085.Fallen Down (Reprise)",
	"086.Don't Give Up",
	"087.Hopes and Dreams",
	"088.Burn in Despair",
	"089.SAVE the WORLD",
	"090.His Theme",
	"092.Reunited",
	"093.Start Menu (full)",
	"094.Respite",
	"095.Bring It In Guys",
	"096.Last Goodbye",
	"097.But the Earth Refused to Die",
	"098.Battle Against a True Hero",
	"099.Power of NEO",
	"100.MEGALOVANIA",
	"101.Good Night",
	"A-10.Abandoned Town",
	"A-10.Dog Hole",
	"A-10.Memory (10 Years Later)",
	"A-10.Pseudo Legendary Tree",
	"A-10.School",
	"A-10.Snowdrift",
	"A-10.Snowed Inn Jazz",
	"A-10.Song That Plays When Somebody Verses Sans",
	"A-10.Strongerer Monsters",
	"A-10.Ultranap",
	"A-10.Underwater Town",
	"A-10.what's up",
	"A-10.Wrong Number Remix",
	"Sound test.Gaster's theme",
	"Sound test.Happy Town",
	"Sound test.Meat Factory",
	"Sound test.Trouble Dingle"
];