Main["Mine"]={};
Main["Mine"]["Lists"]={};
Main["Mine"]["Mine"] = [
	"[OVERLOADED] [Deltarune Chapters combined] - Orchestral [Instrumental]",
	"[OVERLOADED] [Deltarune Chapters combined] - Orchestral",
	"·IN(K)TAKE· Trailer",
	"1K subs Tailer",
	"1K subs",
	"5-4-3-2-Down streat",
	"900 subs",
	"A single man's rehearsal",
	"A strugulling beginning",
	"A terrible joke + Big chaos [Deltarune Chapters combined] - Orchestral",
	"Apres cymical",
	"Band roll",
	"Bassoon tale",
	"Battle Trace",
	"BIG-BACKPAIN - Faynaly & CrystalFoxxie",
	"Blast-Model",
	"Brass Princess - Themes (Introduction + Bring the kingdom to glory + Hello once again)",
	"Buisness gone out of hand",
	"Bumping in",
	"Cannon winter",
	"Cluster cult",
	"Cold corner",
	"Complot Boolea-ttack",
	"Conclussion terms Ver. 2",
	"Conclussion terms",
	"Controversial wrath",
	"cronos center's cristal field",
	"danger classic",
	"daunting feeling",
	"Daylight kingdom diorama [Piano version]",
	"Daylight kingdom diorama",
	"Diest Grand",
	"Dim torches inside",
	"Distance",
	"distant glitter",
	"distorsion trumpet Orchestral Force",
	"DO Orchestral",
	"Doria Gloria",
	"Drag sorrow",
	"Draining your feelings",
	"Dwizzeldilalla Morning",
	"Epic BT",
	"ESMEGiMA But is a boss battle",
	"ESMEGiMA",
	"Exposing my diferent music",
	"Fay Naly Multi Cortes - Intro",
	"Fay-lament - in c major",
	"Fay-lament - in c minor",
	"FayNaly - Order of Honor",
	"Forgotten light",
	"Gradient disappearance. Piano Concerto No. 1",
	"Grain fog",
	"Half harm knight",
	"Harmonizing the simple chords Piano",
	"Harmonizing the simple chords",
	"Hollow hearts of war",
	"Home like palace - Faynaly & CrystalFoxxie",
	"I don't want to go...",
	"Imaginary concept",
	"Incoming machine",
	"Interest modeling",
	"Jester Card",
	"Joyful Experience",
	"just fast",
	"La Maquina Is Comming",
	"Last Hope",
	"Laywire & Wereking [Deltarune Chapters combined] - Orchestral",
	"Light cave",
	"Light course",
	"Long white and bule scarf",
	"Lullaby",
	"Mortal suspension",
	"Multivers Champions Theme",
	"Non confrontable",
	"November",
	"Now Streaming",
	"Offering to my sire",
	"Old castle",
	"Once on shot ver2",
	"Once on shot",
	"Open Field Battle",
	"Organ dance [Organ version]",
	"Organ dance",
	"Overture in 9 over 4",
	"Phase of wind",
	"Polygonal looks",
	"Portal rotion",
	"Provition of decay",
	"Pulverized army",
	"Q.round [Deltarune Chapters combined] - Orchestral",
	"Race+dead_lullaby",
	"Reolanex ver2",
	"Reolanex",
	"Reverse Injuries",
	"Right now i have no ideas sorry",
	"Roll cut",
	"Sadness Crypt",
	"Save me",
	"Save Yourself",
	"School",
	"Sentimental emphasis",
	"Sevilton themes [Deltarune Chapters combined] - Orchestral",
	"Sky grace",
	"slowfication orchestral",
	"Star knight",
	"Stars from the wind",
	"Storm wave",
	"Story needed battles [Deltarune Chapters combined] - Orchestral",
	"tabern",
	"Tale from sa king",
	"The adventure beneath the surface - Stray [fan made - conceptual music]",
	"The Beginning [Remake]",
	"the beginning",
	"the color of the sound",
	"The desert that's made out of crystal",
	"The holydays passing by",
	"The long window",
	"The machinist Ver. 2",
	"The machinist",
	"The new you",
	"The rise of the star blazer - MidnightMunchies",
	"The royal ars kicking [Deltarune Chapters combined] - Orchestral",
	"The shine of a new day strikes you with joy",
	"The stars in my sky",
	"The triumph on my tone",
	"Theories of the past",
	"Ther color - Sorta Force",
	"Time to time, i sleep",
	"Tired of crushed dreams",
	"Tragic re-encounter",
	"United at last",
	"Venus atmospher",
	"Wereking [Deltarune Chapters combined] - Orchestral",
	"Wet memories",
	"Yoserin pice - hard to belive 7&5 over 4",
	"Yoserin-K piano pice 1-b",
	"Yoserin-K piano pice",
	"yumme niki (orchestral room my take)",
	"Обнадеживающий сад",
	"Погоня"
];
Main["Mine"]["Lists"]["·IN(K)TAKE·"] = [
	"·IN(K)TAKE· 01-красный",
	"·IN(K)TAKE· 02-Arancione",
	"·IN(K)TAKE· 03-黄色",
	"·IN(K)TAKE· 04-Limette",
	"·IN(K)TAKE· 05-Vert",
	"·IN(K)TAKE· 06-Ciano",
	"·IN(K)TAKE· 07-Blue",
	"·IN(K)TAKE· 08-紫",
	"·IN(K)TAKE· 09-Nigra",
	"·IN(K)TAKE· 10-Blanco"
];
Main["Mine"]["Lists"]["Deltarune - The (Un) Happy Few"] = [
	"Furmiant",
	"Kxarls",
	"Laugh hall",
	"Not funny experience",
	"Partialy chilling",
	"Rikxard"
];
Main["Mine"]["Lists"]["Detarune - Chapters combined"] = [
	"[OVERLOADED] Intrumental",
	"[OVERLOADED]",
	"A terrible joke",
	"Another one",
	"Attack of the checker queen",
	"Basement",
	"BIG CHAOS (style)",
	"BIG CHAOS [Glamour]",
	"BIG CHAOS",
	"Binary lake",
	"Checker queen",
	"Cheked Mixtape",
	"Crude tempest",
	"Daily days",
	"Don't feed the animals",
	"DRIVEKEY",
	"Elegant move",
	"freedom",
	"granpusler",
	"HA! gose the wheesel",
	"Hey light nerds",
	"It's a cord grove",
	"Laywire",
	"Nighty night",
	"NOW'S YOUR CHANSE TO MAKE",
	"Queen & Kings game board",
	"Rough & Tumble",
	"Sevilton",
	"the knight in fake armor",
	"The power of freedom",
	"The Prophecy",
	"The roxuls are being colored",
	"The royal kerfuffle",
	"True gamer",
	"TV Snow",
	"W A S D",
	"Wearking",
	"WELCOME TO PIECES & PARTS",
	"Wires all tangled up"
];
Main["Mine"]["Lists"]["FNF"] = [
	"Har' the lost",
	"Main garden (inst)",
	"Main garden (vocals)",
	"Main garden",
	"Reo 2 BF Vocals",
	"Reo 2 Inst",
	"Reo 2 R Vocals",
	"Reo 2",
	"Tetra-fatigue (Inst)",
	"Tetra-fatigue (Vocals)",
	"Tetra-fatigue",
	"Обнадеживающий сад (Inst)",
	"Обнадеживающий сад (Vocals)",
	"Обнадеживающий сад"
];
Main["Mine"]["Lists"]["Generic OST Album"] = [
	"Generic []",
	"Generic Ancient Ruins",
	"Generic Boss N-2",
	"Generic Boss",
	"Generic Dangerus Place",
	"Generic Desision",
	"Generic Ethnic Encounter",
	"Generic Field",
	"Generic Forest Village",
	"Generic Secret Boss N-2",
	"Generic Secret Boss",
	"Generic Snowy",
	"Generic Tension",
	"Generic Town"
];
