const mid=false, Main = {
    "Mine": {
        "Lists": {
            "·IN(K)TAKE·": [
                "·IN(K)TAKE· 01-красный",
                "·IN(K)TAKE· 02-Arancione",
                "·IN(K)TAKE· 03-黄色",
                "·IN(K)TAKE· 04-Limette",
                "·IN(K)TAKE· 05-Vert",
                "·IN(K)TAKE· 06-Ciano",
                "·IN(K)TAKE· 07-Blue",
                "·IN(K)TAKE· 08-紫",
                "·IN(K)TAKE· 09-Nigra",
                "·IN(K)TAKE· 10-Blanco"
            ],
            "Deltarune - The (Un) Happy Few": [
                "Furmiant",
                "Kxarls",
                "Laugh hall",
                "Not funny experience",
                "Partialy chilling",
                "Rikxard"
            ],
            "Detarune - Chapters combined": [
                "[OVERLOADED] Intrumental",
                "[OVERLOADED]",
                "A terrible joke",
                "Another one",
                "Attack of the checker queen",
                "Basement",
                "BIG CHAOS (style)",
                "BIG CHAOS [Glamour]",
                "BIG CHAOS",
                "Binary lake",
                "Checker queen",
                "Cheked Mixtape",
                "Crude tempest",
                "Daily days",
                "Don't feed the animals",
                "DRIVEKEY",
                "Elegant move",
                "freedom",
                "granpusler",
                "HA! gose the wheesel",
                "Hey light nerds",
                "It's a cord grove",
                "Laywire",
                "Nighty night",
                "NOW'S YOUR CHANSE TO MAKE",
                "Queen & Kings game board",
                "Rough & Tumble",
                "Sevilton",
                "the knight in fake armor",
                "The power of freedom",
                "The Prophecy",
                "The roxuls are being colored",
                "The royal kerfuffle",
                "True gamer",
                "TV Snow",
                "W A S D",
                "Wearking",
                "WELCOME TO PIECES & PARTS",
                "Wires all tangled up"
            ],
            "FNF": [
                "Har' the lost",
                "Main garden (inst)",
                "Main garden (vocals)",
                "Main garden",
                "Reo 2 BF Vocals",
                "Reo 2 Inst",
                "Reo 2 R Vocals",
                "Reo 2",
                "Tetra-fatigue (Inst)",
                "Tetra-fatigue (Vocals)",
                "Tetra-fatigue",
                "Обнадеживающий сад (Inst)",
                "Обнадеживающий сад (Vocals)",
                "Обнадеживающий сад"
            ],
            "Generic OST Album": [
                "Generic []",
                "Generic Ancient Ruins",
                "Generic Boss N-2",
                "Generic Boss",
                "Generic Dangerus Place",
                "Generic Desision",
                "Generic Ethnic Encounter",
                "Generic Field",
                "Generic Forest Village",
                "Generic Secret Boss N-2",
                "Generic Secret Boss",
                "Generic Snowy",
                "Generic Tension",
                "Generic Town"
            ]
        },
        "Mine": [
			"Sunset painting",
			"Doria Gloria",
			"Non confrontable",
			"Once on shot ver2",
			"Distance",
			"Light course",
			"United at last",
			"Bassoon tale",
			"Organ dance [Organ version]",
			"Forgotten light",
			"The Beginning [Remake]",
			"Tired of crushed dreams",
			"Organ dance",
			"Diest Grand",
			"daunting feeling",
			"Daylight kingdom diorama",
			"Daylight kingdom diorama [Piano version]",
			"Dwizzeldilalla Morning",
			"The new you",
			"Provition of decay",
			"[OVERLOADED] [Deltarune Chapters combined] - Orchestral",
			"[OVERLOADED] [Deltarune Chapters combined] - Orchestral [Instrumental]",
			"[OVERLOADED] Trailer song",
			"Grain fog",
			"Phase of wind",
			"Sky grace",
			"Reverse Injuries",
			"Last Hope",
			"Conclussion terms Ver. 2",
			"Light cave",
			"Dim torches inside",
			"Drag sorrow",
			"Half harm knight",
			"Overture in 9 over 4",
			"Exposing my diferent music",
			"BIG-BACKPAIN - Faynaly & CrystalFoxxie",
			"Home like palace - Faynaly & CrystalFoxxie",
			"·IN(K)TAKE· Trailer",
			"Incoming machine",
			"Cluster cult",
			"Wereking [Deltarune Chapters combined] - Orchestral",
			"Interest modeling",
			"Offering to my sire",
			"Once on shot",
			"The royal ars kicking [Deltarune Chapters combined] - Orchestral",
			"Sadness Crypt",
			"Sevilton themes [Deltarune Chapters combined] - Orchestral",
			"The holydays passing by",
			"Sentimental emphasis",
			"Pulverized army",
			"Old castle",
			"Blast-Model",
			"A strugulling beginning",
			"Hollow hearts of war",
			"Story needed battles [Deltarune Chapters combined] - Orchestral",
			"Polygonal looks",
			"Laywire & Wereking [Deltarune Chapters combined] - Orchestral",
			"Q.round [Deltarune Chapters combined] - Orchestral",
			"A terrible joke + Big chaos [Deltarune Chapters combined] - Orchestral",
			"Brass Princess - Themes (Introduction + Bring the kingdom to glory + Hello once again)",
			"5-4-3-2-Down streat",
			"Draining your feelings",
			"Band roll",
			"Apres cymical",
			"Cold corner",
			"The machinist Ver. 2",
			"Fay Naly Multi Cortes - Intro",
			"Yoserin pice - hard to belive 7&5 over 4",
			"Fay-lament - in c minor",
			"Fay-lament - in c major",
			"I don't want to go...",
			"Bumping in",
			"The triumph on my tone",
			"Multivers Champions Theme",
			"cronos center's cristal field",
			"FayNaly - Order of Honor",
			"Jester Card",
			"Lullaby",
			"Tale from sa king",
			"Mortal suspension",
			"Long white and bule scarf",
			"Complot Boolea-ttack",
			"Portal rotion",
			"Roll cut",
			"Storm wave",
			"Cannon winter",
			"Controversial wrath",
			"Buisness gone out of hand",
			"Conclussion terms",
			"The stars in my sky",
			"Ther color - Sorta Force",
			"Epic BT",
			"The rise of the star blazer - MidnightMunchies",
			"Tragic re-encounter",
			"Wet memories",
			"The adventure beneath the surface - Stray [fan made - conceptual music]",
			"slowfication orchestral",
			"ESMEGiMA But is a boss battle",
			"1K subs",
			"1K subs Tailer",
			"Gradient disappearance. Piano Concerto No. 1",
			"Обнадеживающий сад",
			"Yoserin-K piano pice 1-b",
			"The desert that's made out of crystal",
			"The long window",
			"Now Streaming",
			"Open Field Battle",
			"The shine of a new day strikes you with joy",
			"ESMEGiMA",
			"Погоня",
			"La Maquina Is Comming",
			"Reolanex ver2",
			"Time to time, i sleep",
			"distorsion trumpet Orchestral Force",
			"Harmonizing the simple chords Piano",
			"Harmonizing the simple chords",
			"the color of the sound",
			"900 subs",
			"distant glitter",
			"A single man's rehearsal",
			"Imaginary concept",
			"just fast",
			"The machinist",
			"tabern",
			"Theories of the past",
			"Yoserin-K piano pice",
			"Save Yourself",
			"Save me",
			"Reolanex",
			"Stars from the wind",
			"Right now i have no ideas sorry",
			"Battle Trace",
			"Race+dead_lullaby",
			"the beginning",
			"Star knight",
			"School",
			"November",
			"Joyful Experience",
			"DO Orchestral",
			"danger classic",
			"yumme niki (orchestral room my take)",
			"Venus atmospher"
        ]
    },
    "Cover Arrangements": [
		"Megalo Clamour - Lunaxis Ver. 2",
		"A Million Gruesome Ways To Die - Billie Bust Up [Instrumental]",
		"A Million Gruesome Ways To Die - Billie Bust Up",
		"Triple Trouble [No FNF Vocals] Ver. 2",
		"Triple Trouble Ver. 2",
		"Main theme - Bad Piggies ver. 2",
		"The Toybox - Stupendium",
		"Kaboomberg - ToonTown Ver. 2",
		"BITE [FERNAN MIX] [No FNF Vocals]",
		"BITE [FERNAN MIX]",
		"Lagtrain - 稲葉曇 [Instrumental]",
		"Lagtrain - 稲葉曇",
		"Dire Dire Docks - SM64 Ver. 2",
		"Happy Birthday",
		"Nightmare Knight - Cucumber quest (Toby fox) Ver. 2 ",
		"Silly Billy [No FNF Vocals]",
		"Silly Billy [Inst]",
		"Silly Billy",
		"Your Contract Has Expired - A Hat In Time Ver. 2",
		"Your Contract Has Expired {hard} - A Hat In Time Ver. 2",
		"Final chance [Phase 4] - Disbelief Papyrus",
		"Backbone [Phase 3] - Disbelief Papyrus Ver. 2",
		"Megalo strikes back [Phase 2] - Disbelief Papyrus Ver. 2",
		"Interstellar Retribution [Phase 1] - Disbelief Papyrus Ver. 2",
		"Open up your eyes - My little pony (The Movie)",
		"Open up your eyes - My little pony (The Movie) [Instrumental]",
		"The Minister (Vision Crew's) - Deltarune Chapter 5 UST",
		"Balrog's Theme - Cave Story",
		"Blooming revolver (Orchestral arragment) - Deltarune UST",
		"Wart - Super Mario Bros 2 [Extended]",
		"I've Had Enough of You - Billie Bust Up [Instrumental]",
		"I've Had Enough of You - Billie Bust Up",
		"Heaven Says - Deltarune UST Ver. 2",
		"Count What You Have Now - Mariya Takeuchi",
		"Anarchy Rainbow - Splatoon 3 Ver. 2 [Choir interpretation]",
		"Anarchy Rainbow - Splatoon 3 Ver. 2 [Instrumental]",
		"Anarchy Rainbow - Splatoon 3 Ver. 2",
		"HARD DRIVE - Griffinilla [Instrumental]",
		"Push Your Limits - Brian Michael Hinds [Instrumental]",
		"Blooming revolver - Deltarune UST",
		"Push Your Limits - Brian Michael Hinds",
		"Don't Ever Forget - Pokemon Mystery Dungeon (Explorers of Sky)",
		"Coconut - Jayfoo [Doodley Soundtrack, Vol. 1]",
		"Lavender Town - Pokemon Red, Blue, Green & Yellow",
		"PokeWalker - Pokemon Heart Gold & Soul Silver",
		"Kalos Region - Pokemon X & Y",
		"Driftveil city - Pokemon Black & White",
		"Rolling Down the Street - Fearofdark",
		"Avast Your Ass - Kitsune²",
		"HARD DRIVE - Griffinilla",
		"Piranha Plants on Parade - Super Mario Wonder",
		"Just look my way - Helluva Boss [Instrumental]",
		"Just look my way - Helluva Boss",
		"柴又 (Shibamata) - Dot nigou",
		"Nigh of nights - Touhou project",
		"Zero Two - Kirby 64 (The Crystal Shards)",
		"Gourmet Race - Kirby Super star",
		"Main theme - Wii Sports",
		"U.N. Owen was her - Touhou Project",
		"Marx's Theme - Kirby Super star",
		"Littleroot Town - Pokemon Ruby & Sapphire & Emerald",
		"Horse racing - Chen jun ver.2 ",
		"wild battle - Pokemon Ruby & Sapphire & Emerald",
		"Jinora's light (Lotus Despair) - Legend of Korra",
		"Hijo de la luna - Mecano ver. 2",
		"Battle (destruction) - Shin Megami Tensei V",
		"Colgera - TLOZ TOTK",
		"Deerclops (The E.F.S. of Winter) - Terraria",
		"Stay With Me - Miki Matsubara [instrumental]",
		"Stay With Me - Miki Matsubara",
		"Idol - YOASOBI Ver.2 [Instrumental]",
		"Idol - YOASOBI Ver.2",
		"YOUR LAST GIFT - Local H00ligan",
		"Idol - YOASOBI",
		"Just the two of us - Grover Washington, Jr. (feat. Bill Withers)",
		"Darkest Lord - Miitopia ver. 2",
		"Daisy bell (Bicycle build for two) - Harry Dacre",
		"Yap Squad [No FNF Vocals]",
		"Yap Squad",
		"Yo buddy - Deltarune [The Other Puppet]",
		"GRAND ILLUSsSIONSsS - Deltarune Chapter 3 UST",
		"Killer Kueen Bites The Dust - Deltarune [Chapter Rewritten]",
		"Area Zero - Pokémon Scarlet & Violet",
		"Area Zero - Pokémon Scarlet & Violet Ver. 2",
		"KING (Gumi) - Kanaria [Instrumental]",
		"KING (Gumi) - Kanaria",
		"The Killer Spin (Orchestral arragment) - Deltarune UST",
		"The Killer Spin - Deltarune UST",
		"Finding another medium (another medium Arragment) - Undertale",
		"GIGA プリン - Deltarune [The Other Puppet] Ver. 2",
		"It's been so long - The living tombstone [FNAF]",
		"Ei Mori Roujke - Nonesuch (Bulgarian female choir)",
		"His World (Sonic's Theme) - Sonic the Hedgehog [Instrumental]",
		"His World (Sonic's Theme) - Sonic the Hedgehog",
		"ANIMAL IN ME - Solence Ver. 2",
		"Credits song for my death - vivivivivi Ver. 2",
		"Gang-Plank Galleon - Super Smash Bros. Ultimate",
		"Gerudo Valley - TLOZ OOT ver. 2",
		"La Gozadera - Gente de Zona (ft. Marc Anthony)",
		"La Gozadera - Gente de Zona (ft. Marc Anthony) Instrumental",
		"Spyro's Adventure - Skylanders",
		"Main Theme - Terminator Genisys",
		"Main Theme - Skylanders SuperChargers",
		"Forgotten One Nyx - Pokémon Insurgence",
		"Wart - Super Mario Bros 2",
		"OFFICIAL WAY - Deltarune Chapter 3 UST",
		"PEACHES - [Jack Black - BOWSER] The super mario movie [inst]",
		"PEACHES - [Jack Black - BOWSER] The super mario movie",
		"Megalo Strike Back - Earthbound Halloween hack",
		"Ashfaghma ot bantiem (Bergentrückung Arragment) - Undertale",
		"Wielder Volo Battle - Pokemon Arceus ver. 2",
		"Shala's Theme - Dream Devourer [Anti-Remix]",
		"Louane - JOUR 1",
		"Yap Squad [Inst]",
		"Area Zero Wild Battle - Pokémon Scarlet & Violet",
		"Demon castle dracula - Super Castlevania IV",
		"CREATIVE FREEDOM - U.Z Inu",
		"Metatron - Shin Megami Tensei III Nocturne",
		"Dracula's Keep - Super Castlevania IV",
		"BIG BANG (Updated Version) - Deltarune [Chapter Rewritten]",
		"Law - Shin Megami Tensei III Nocturne",
		"The Grand Finale - Mario & Luigi Bowser inside story",
		"Wet Hands - Minecraft",
		"BATTLE AGAINST THE WORLD - Deltarune [Chapter Rewritten]",
		"Main theme - El Vendedor de Humo - The Smoke Seller (Recreation & Cover)",
		"Lorule Castle - TLOZ ALBW ver. 2",
		"The Piano Duet - Corpse Bride",
		"Schoolhouse Trouble! - Baldi's Basics Classic Remastered",
		"Heaven Says - Deltarune UST",
		"I CAN Y̴̘͘O̶U ̴̛̲̓C̶̭͒̿Ḁ̷̖̒N̵̻̽̊ - Deltarune [Chapter Rewritten]",
		"BIG BANG - Deltarune [Chapter Rewritten]",
		"Horse racing - Chen jun",
		"Bonnqueet grand queen (Queen's themes Arragments) - Deltarune",
		"Deal Gone Wrong choir catastrhopy (Deal gone wrong Arragment) - Deltarune",
		"Lost, forgotten, down Friend (Lost girl - arragment) - Deltarune",
		"Low Kromer (Big Shot Arragment) - Deltarune",
		"Main Theme - Skylanders The Swap Force",
		"Hell March 3 - Red Alert 3",
		"Champion Battle - Pokemon Insurgence",
		"Calamari Inkantation 3MIX - Splatoon 3 [instrumental]",
		"Calamari Inkantation 3MIX - Splatoon 3",
		"God Save The Queen - UK",
		"Hijo de la luna - Mecano",
		"Addict - Hazbin Hotel",
		"Somebody else - Kevin Temmer",
		"The Opening of Every Animated Film - Kevin Temmer Tunes",
		"Merry Go Round Life - howl's castle ver. 2",
		"Battle (guardian) - TLOZ BOTW",
		"Boogieman",
		"Boogieman [No FNF Vocals]",
		"The Crisis of Red and Green - Mario & Luigi [Partners in Time]",
		"Lost Woods - TLOZ OOT",
		"No More Deals - Undetale (No More Deals) ver. 2",
		"Anarchy Rainbow - Splatoon 3 [Instrumental]",
		"Anarchy Rainbow - Splatoon 3 [Choir interpretation]",
		"Anarchy Rainbow - Splatoon 3",
		"Gerudo Valley - TLOZ OOT",
		"Clock Town Day 1 - TLOZ MM",
		"Kokiri Forest - TLOZ OOT",
		"Cool, cool mountain - SM64",
		"Stolas Singss - Helluva Boss [Instrumental]",
		"Stolas Sings - Helluva Boss",
		"Stolas Singss [Dark] - Helluva Boss [Instrumental]",
		"Stolas Sings [Dark] - Helluva Boss",
		"Ultimate Bowser - MS64",
		"Bowser Road - MS64",
		"CP Violation - Half Life 2",
		"Merry Go Round Super - SM64",
		"Heartaches - Al-Bowlly",
		"Delete this tweet - Trash cans - Kevin Temmer",
		"The World Revolving Another remix (The World Revolving - Arragment) - Deltarune",
		"Laugh Track - Deltarune Chapter 3 UST ver. 2",
		"Staff Rol - SM64",
		"Slider - SM64",
		"Dire Dire Docks - MS64",
		"Flowering Night - Touhou Project",
		"Echo [Gumi Ingles] - Crusher-P",
		"Bad Apple - Touhou project ver. 2",
		"Rolling Girl - Wowaka ver.2",
		"Jedi Temple March - StarWars",
		"The Nowhere King - Centaurworld [Instrumental]",
		"The Nowhere King - Centaurworld",
		"No More Deals - Undetale (No More Deals)",
		"Super Idol - 105",
		"Left Unchecked [No FNF Vocals]",
		"Left Unchecked",
		"MonoChrome [No FNF Vocals]",
		"MonoChrome",
		"Dracula's theme - Castelvania 4",
		"Giants - Skylander Giants",
		"Savior of the Waking World - Homestuck Vol 5",
		"Bloody Tears - Castelvania",
		"Sis Puella Magica - Puella Magi Madoka Magica",
		"Opposing Bloodlines - Castlevania 64",
		"Dialga's Fight to the Finish! - Pokemon Mystery Dungeon Explorers of Time Darkness",
		"Upward Movement (Dave Own) - HomeStuck Vol 2",
		"Your Contract Has Expired - A Hat In Time",
		"Your Contract Has Expired {hard} - A Hat In Time",
		"Backbone [Phase 3] - Disbelief Papyrus",
		"Interstellar Retribution [Phase 1] - Disbelief Papyrus",
		"Megalo strikes back [Phase 2] - Disbelief Papyrus",
		"Lorule Castle - TLOZ ALBW",
		"Song of Storms - TLOZ OOF",
		"Grass Skirt Chase - SpongeBob SquarePants",
		"The slaughter continues - Undertale (Last breath)",
		"From the Shadows - Shovel Knight",
		"Laugh Track - Deltarune Chapter 3 UST",
		"Phantasm [No FNF Vocals]",
		"Phantasm",
		"Strike the earth - Shovel Knight",
		"An Enigmatic Encounter - Undertale (Last breath) ver. 2",
		"Duel of the Fates - StarWars",
		"The Boiler - ToonTown Rewritten",
		"Kaboomberg - ToonTown",
		"You smell of death flowers - Vslush",
		"Inferno - Fire Force",
		"Tower Battle - Pokemon shield & Sword",
		"Pirates sea [unused track] - PVZ2",
		"Darkness Falls & Faint Courage - Deltarune",
		"Pirate seas - PVZ2",
		"Main theme - Papers Please",
		"Credits song for my death - vivivivivi",
		"Nightmare Knight - Cucumber quest (Toby fox)",
		"Deal Gone Wrong (violin fading) - Deltarune",
		"Goodbye To A World - Poter Robinson",
		"We Dont Talk About Bruno No Se Habla De Bruno - Encanto [Instrumental]",
		"We Dont Talk About Bruno - Encanto",
		"No se habla de bruno - Encanto",
		"GIGA プリン - Deltarune [The Other Puppet]",
		"Megalo Clamour - Kibo",
		"You Will Be Ok - Helluva Boss",
		"Never gonna give you up - Rick Astley",
		"Marble Machine - Wintergatan",
		"Vitality - Helltaker",
		"The Great Sage's - Miitopia",
		"We are - One Pice",
		"Road Less Taken Real - Persona Q2",
		"Darkest Lord - Miitopia",
		"Wielder Volo Battle - Pokemon Arceus",
		"PS5 - MrMoMMusic (feat. Alan Walker)",
		"Main theme - Bad Piggies",
		"Discord - Eurobeat",
		"Library Piano - Luigi's Mansion Dark Moon",
		"Dj music man - FNAF SB",
		"Bad Apple - Touhou project ",
		"Sweden Minecraft",
		"MTC - S3RL",
		"ANIMAL IN ME  - Solence",
		"Daycare - FNAF SB",
		"Perseverance - Gris",
		"Triple Trouble [No FNF Vocals]",
		"Cascade - HomeStuck Vol 8",
		"Missa langosta - Missa sinfonia",
		"Triple Trouble",
		"Even in Death - Homestuck Vol 7",
		"Relight [Gaster's theme] - Underverse",
		"A Sunny Day Is Watching Over You - Nekojishi",
		"Merry Go Round Life - howl's castle",
		"Sidon's theme - TLOZ BOTW",
		"An Enigmatic Encounter - Undertale (Last breath)",
		"You'er Truly A Real Boy! - Deltarune [fan UST]",
		"Spooky scary skeletons - Andrew Gold [Happy halloween]",
		"Spooky scary skeletons - Andrew Gold",
		"Rolling Girl - Wowaka",
		"Attack of the Killer Queen Remix (Attack of the Killer Queen Arragment) - Deltarune"
    ],
    "Cover Albums": {
        "OMORI": [
			"001.Title",
			"002.WHITE SPACE",
			"003.Lost At A Sleepover",
			"004.Spaces In-between",
			"005.By Your Side.",
			"006.Let's Get Together Now!",
			"007.100 Sunny",
			"008.Trouble Brewing",
			"009.Push & Shove",
			"010.So, How'd We Do_",
			"011.It's Okay To Try Again...",
			"012.Trees...",
			"013.A Home For Flowers (Tulip)",
			"014.Acrophobia",
			"015.Tussle Among Trees",
			"016.A Place By A Lake",
			"017.Forest Chillin'",
			"018.Poems In The Fog",
			"019.Space Road 1979",
			"020.See In Your Fantasy"
        ],
        "Undertale": [
            "-.Absolutely Overfamiliar Shrine",
            "-.Before the Story",
            "-.Dance of dog",
            "-.Dog casino",
            "-.King Description",
            "-.Mad Mew Mew",
            "-.Mysterious Shrine",
            "-.Sigh of Dog",
            "-.Star",
            "-.The Wrong Number Song",
            "-.Toby Room",
            "001.Once Upon a Time",
            "002.Start Menu",
            "003.Your Best Friend",
            "004.Fallen Down",
            "005.Ruins",
            "006.Uwa!! So Temperate",
            "007.Anticipation",
            "008.Unnecessary Tension",
            "009.Enemy Approaching",
            "010.Ghost Fight",
            "011.Determination",
            "012.Home",
            "013.Home (Music Box)",
            "014.Heartache",
            "015.sans.",
            "016.Nye heh heh!",
            "017.Snowy",
            "018.Uwa So Holiday",
            "019.Dogbass",
            "020.Mysterious Place",
            "021.Dog Song",
            "022.Snowdin Town",
            "023.Shop",
            "024.Bonetrousle",
            "025.Dating Start",
            "026.Dating Tense!",
            "027.Dating Fight!",
            "028.Premonition",
            "029.Danger Mystery",
            "030.Undyne",
            "031.Waterfall",
            "032.Run!",
            "033.Quiet Water",
            "034.Memory",
            "035.Bird That Carries You Over A Disproportionately Small Gap",
            "036.Dummy!",
            "037.Pathetic House",
            "038.Spooktune",
            "039.Spookwave",
            "040.Ghouliday",
            "041.Chill",
            "042.Thundersnail",
            "043.Temmie Village",
            "044.Tem Shop",
            "045.NGAHHH!!",
            "046.Spear of Justice",
            "047.Ooo",
            "048.Alphys",
            "049.It's Showtime",
            "050.Metal Crusher",
            "051.Another Medium",
            "052.Uwa!! So HEATS!!",
            "053.Stronger Monsters",
            "054.Hotel",
            "055.Can You Really Call This A Hotel I Didn't Receive A Mint On My Pillow Or Anything",
            "056.Confession",
            "057.Live Report",
            "058.Death Report",
            "059.Spider Dance",
            "060.Wrong Enemy",
            "061.Oh! One True Love",
            "062.Oh! Dungeon",
            "063.It's Raining Somewhere Else",
            "064.CORE Approach",
            "065.CORE",
            "066.Last Episode",
            "067.Oh My...",
            "068.Death by Glamour",
            "069.For the Fans",
            "071.Undertale",
            "072.Song That Might Play When You Fight Sans",
            "074.Small Shock",
            "076.Bergentrückung",
            "077.ASGORE",
            "078.You Idiot",
            "079.Your Best Nightmare",
            "080.Finale",
            "081.An Ending",
            "082.She's Playing Piano",
            "083.Here We Are",
            "084.Amalgam",
            "085.Fallen Down (Reprise)",
            "086.Don't Give Up",
            "087.Hopes and Dreams",
            "088.Burn in Despair",
            "089.SAVE the WORLD",
            "090.His Theme",
            "092.Reunited",
            "093.Start Menu (full)",
            "094.Respite",
            "095.Bring It In Guys",
            "096.Last Goodbye",
            "097.But the Earth Refused to Die",
            "098.Battle Against a True Hero",
            "099.Power of NEO",
            "100.MEGALOVANIA",
            "101.Good Night",
            "A-10.Abandoned Town",
            "A-10.Dog Hole",
            "A-10.Memory (10 Years Later)",
            "A-10.Pseudo Legendary Tree",
            "A-10.School",
            "A-10.Snowdrift",
            "A-10.Snowed Inn Jazz",
            "A-10.Song That Plays When Somebody Verses Sans",
            "A-10.Strongerer Monsters",
            "A-10.Ultranap",
            "A-10.Underwater Town",
            "A-10.what's up",
            "A-10.Wrong Number Remix",
            "Sound test.Gaster's theme",
            "Sound test.Happy Town",
            "Sound test.Meat Factory",
            "Sound test.Trouble Dingle"
        ],
        "Dungeons of Aether": [
            "007.First Quarry (Area 1)",
            "008.Ground Breakers (Battle 1)"
        ],
        "FNF Smoke 'Em Out Struggle": [
            "Fading",
            "Headache",
            "Nerves",
            "Release"
        ],
        "FNF Vs. witthy": [
            "Ballistic",
            "Ballistic[No FNF Vocals]",
            "Lo-Fight [No FNF Vocals]",
            "Lo-Fight",
            "Low Rise [No FNF Vocals]",
            "Low Rise",
            "Overhead",
            "Underground"
        ],
        "(OLD) FNF Vs. Retrospecter": [
            "Acidiron [No FNF Vocals]",
            "Acidiron",
            "Fuzzy Feeling [No FNF Vocals]",
            "Fuzzy Feeling",
            "HeartMelter [no fnf voice]",
            "HeartMelter",
            "Overtime [no fnf voice]",
            "Overtime",
            "Preppy [no fnf voice]",
            "Preppy",
            "Preseason [no fnf voice]",
            "Preseason",
            "Retro [no fnf voice]",
            "Retro",
            "Satisfracture [no fnf voice]",
            "Satisfracture",
            "Sigma [no fnf voice]",
            "Sigma",
            "Spectral [no fnf voice]",
            "Spectral"
        ],
        "(OLD) Undertale": [
            "-.Absolutely Overfamiliar Shrine",
            "-.Before the Story -482005294-",
            "-.Before the Story",
            "-.Dance of dog",
            "-.Dog casino",
            "-.King Description",
            "-.Mad Mew Mew",
            "-.Mysterious Shrine",
            "+.mus_st_him",
            "001.Once Upon a Time",
            "002.Start Menu",
            "003.Your Best Friend",
            "004.Fallen Down Ver. 2",
            "004.Fallen Down",
            "005.Ruins Ver. 2",
            "005.Ruins",
            "006.Uwa!! So Temperate",
            "007.Anticipation",
            "008.Unnecessary Tension",
            "009.Enemy Approaching",
            "010.Ghost Fight",
            "011.Determination Ver. 2",
            "011.Determination",
            "012.Home",
            "013.Home (Music Box)",
            "014.Heartache Ver. 2",
            "014.Heartache",
            "015.sans.",
            "016.Nye heh heh! Ver. 2",
            "016.Nye heh heh!",
            "017.Snowy",
            "018.Uwa So Holiday",
            "020.Mysterious Place",
            "021.Dog Song",
            "022.Snowdin Town",
            "023.Shop Ver. 2",
            "023.Shop",
            "024.Bonetrousle Ver. 2",
            "024.Bonetrousle",
            "025.Dating Start",
            "026.Dating Tense!",
            "027.Dating Fight!",
            "028.Premonition",
            "029.Danger Mystery",
            "030.Undyne",
            "031.Waterfall",
            "032.Run!",
            "033.Quiet Water",
            "034.Memory",
            "035.Bird That Carries You Over A Disproportionately Small Gap ver. 2",
            "035.Bird That Carries You Over A Disproportionately Small Gap",
            "036.Dummy!",
            "037.Pathetic House",
            "038.Spooktune",
            "039.Spookwave",
            "040.Ghouliday",
            "041.Chill",
            "042.Thundersnail",
            "043.Temmie Village ver. 2",
            "043.Temmie Village",
            "044.Tem Shop",
            "045.NGAHHH!!",
            "046.Spear of Justice",
            "047.Ooo",
            "048.Alphys",
            "049.It's Showtime",
            "050.Another Medium ver. 2",
            "050.Another Medium",
            "051.Metal Crusher",
            "052.Uwa!! So HEATS!!",
            "053.Hotel Ver. 2",
            "053.Hotel",
            "054.Stronger Monsters",
            "055.Can You Really Call This A Hotel I Didn't Recieve A Mint On My Pillow Or Anything",
            "056.Confession",
            "057.Live Report",
            "058.Death Report ver.2",
            "058.Death Report",
            "059.Spider Dance",
            "060.Wrong Enemy",
            "061.Oh! One True Love",
            "062.Oh! Dungeon",
            "063.It's Raining Somewhere Else",
            "064.CORE Approach",
            "065.CORE",
            "066.Last Episode",
            "067.Oh My",
            "068.Death by Glamour ver. 2",
            "068.Death by Glamour",
            "069.For the Fans",
            "071.Undertale ver. 2",
            "071.Undertale",
            "072.Song That Might Play When You Fight Sans",
            "074.Small Shock",
            "076.Bergentrückung Ver. 2",
            "076.Bergentrückung",
            "077.ASGORE ver. 2",
            "077.ASGORE",
            "078.You Idiot",
            "079.Your Best Nightmare ver. 2",
            "079.Your Best Nightmare",
            "080.Finale",
            "081.An Ending",
            "082.She's Playing Piano",
            "083.Here We Are",
            "084.Amalgam ver. 2",
            "084.Amalgam",
            "085.Fallen Down (Reprise) ver. 2",
            "085.Fallen Down (Reprise)",
            "086.Don't Give Up",
            "087.Hopes and Dreams ver. 2",
            "087.Hopes and Dreams",
            "088.Burn in Despair",
            "089.SAVE the WORLD Ver. 2",
            "089.SAVE the WORLD",
            "090.His Theme",
            "092.Reunited ver. 2",
            "092.Reunited",
            "093.Start Menu (full)",
            "094.Respite",
            "095.Bring It In Guys Ver. 2",
            "095.Bring It In Guys",
            "096.Last Goodbye Ver. 2",
            "096.Last Goodbye",
            "097.But the Earth Refused to Die ver. 2",
            "097.But the Earth Refused to Die",
            "098.Battle Against a True Hero Ver. 2",
            "098.Battle Against a True Hero Ver. 3",
            "098.Battle Against a True Hero",
            "099.Power of NEO",
            "100.MEGALOVANIA Ver. 2",
            "100.MEGALOVANIA",
            "101.Good Night"
        ],
		"(OLD) Deltarune Chapter 1": [
            "-.Char Joined",
            "-.Man",
            "-.Thrash Rating",
            "01.ANOTHER HIM",
            "02.Beginning",
            "03.School",
            "04.Susie",
            "05.The Door",
            "06.Cliffs",
            "07.The Chase",
            "08.The Legend",
            "09.Lancer ver. 2",
            "09.Lancer",
            "10.Rude buster",
            "11.Empty Town",
            "13.Field of Hopes and Dreams ver. 2",
            "13.Field of Hopes and Dreams",
            "14.Fanfare (from Rose of Winter) short",
            "14.FanFare (from Rose of Winter)",
            "15.Lantern",
            "16.I'm very bad",
            "17.Chekers Dance",
            "18.Quiet Autumn",
            "19.Scarlet Forest",
            "20.Thrash Machine",
            "21.VS. Lancer",
            "22.Basement",
            "23.Imminent Death",
            "24.VS. Susie",
            "25.Card Castle",
            "26.Rouxls Kaard-Ruruskado",
            "27.April 2012",
            "28.Hip shop",
            "29.Gallery",
            "30.Chaos King ver. 2",
            "30.Chaos King",
            "31.Darkness Falls",
            "32.The Circus",
            "33.The World Revolving ver. 2",
            "33.The World Revolving",
            "34.Friendship",
            "35.THE HOLY",
            "36.Your Power",
            "37.A Town Called Hometown",
            "38.You Can Always Come Home",
            "39.Don't Forget",
            "40.Before the Story -482005294-",
            "40.Before the Story",
            "42.sans."
        ],
        "(OLD) Deltarune Chapter 2": [
            "-.A-pplause for Berdly",
            "-.Berdly Battle (Really Tense Heartbeat Momento Version)",
            "-.Cyber Battle",
            "-.Cybercity (Alt)",
            "-.D.ogg ",
            "01.Faint Glow",
            "02.Girl Next Door",
            "03.My Castle Town Ver. 2",
            "03.My Castle Town",
            "05.Queen Ver. 2",
            "05.Queen Ver. 3",
            "05.Queen",
            "06.A Cybers World Ver. 2",
            "06.A Cybers World",
            "07.A Simple Diversion ver. 2",
            "07.A Simple Diversion",
            "08.Almost To The Guys! Ver. 2",
            "08.Almost To The Guys!",
            "10.When I Get Mad I Dance Like This",
            "11.Toby Fox & Lena Raine - Cyber Battle",
            "12.When I Get Happy I Dance Like This",
            "13.Sound Studio",
            "14.Berdly",
            "15.Smart Race ver. 2",
            "15.Smart Race",
            "16.Faint Courage (Game Over) Ver. 2",
            "16.Faint Courage (Game Over) Ver. 3",
            "16.Faint Courage (Game Over)",
            "16.Faint Courage (Game Over)B side",
            "17.WELCOME TO THE CITY",
            "18.Mini Studio",
            "19.Holyday Studio",
            "20.Cool Mixtape",
            "21.HEY EVERY!",
            "22.Spamtom",
            "23.NOW'S YOUR CHANCE TO BE A",
            "24.Elegant Entrance",
            "25.Bluebird of Misfortune PIANO & VIOLIN",
            "25.Bluebird of Misfortune",
            "26.Pandora Palace Ver. 2",
            "26.Pandora Palace",
            "27.KEYGEN",
            "28.Acid Tunnel of Love",
            "29.It's Pronounced ¡Rules! ver. 2",
            "29.It's Pronounced ¡Rules!",
            "30.Lost Girl",
            "31.Ferris Wheel",
            "32.Toby Fox & Lena Raine & Marcy Nabors - Attack of the Killer Queen",
            "33.Giga Size",
            "34.Powers Combined",
            "35.Knock You Down",
            "36.The Dark Truth Ver. 2",
            "36.The Dark Truth",
            "37.Digital Roots",
            "38.Deal Gone Wrong ver. 2",
            "38.Deal Gone Wrong",
            "39.Big Shot ver. 2",
            "39.Big Shot ver. 3",
            "39.Big Shot",
            "40.A Real Boy!",
            "41.Dialtone",
            "42.sans.",
            "43.Napsta Alarm",
            "45.Until next time ver. 2",
            "45.Until next time"
        ]
    },
    "Memes": [
        "among us remix (my cumbia)",
        "Cool Remix extended",
        "Cool Remix",
        "Main theme - Wii Sports (Minor key)",
        "PS5 [Fortnite Battle Pass] - MrMoMMusic (feat. Alan Walker)",
        "Smash Susie",
		"WhatsappLovania"
    ]
};