const Main = {
    "Mine": {
        "Lists": {
            "·IN(K)TAKE·": [
                "·IN(K)TAKE· 01-красный",
                "·IN(K)TAKE· 02-Arancione",
                "·IN(K)TAKE· 03-黄色",
                "·IN(K)TAKE· 04-Limette",
                "·IN(K)TAKE· 05-Vert",
                "·IN(K)TAKE· 06-Ciano",
                "·IN(K)TAKE· 07-Blue",
                "·IN(K)TAKE· 08-紫",
                "·IN(K)TAKE· 09-Nigra",
                "·IN(K)TAKE· 10-Blanco"
            ],
            "Deltarune - The (Un) Happy Few": [
                "Furmiant",
                "Kxarls",
                "Laugh hall",
                "Not funny experience",
                "Partialy chilling",
                "Rikxard"
            ],
            "Detarune - Chapters combined": [
                "[OVERLOADED] Intrumental",
                "[OVERLOADED]",
                "A terrible joke",
                "Another one",
                "Attack of the checker queen",
                "Basement",
                "BIG CHAOS (style)",
                "BIG CHAOS [Glamour]",
                "BIG CHAOS",
                "Binary lake",
                "Checker queen",
                "Cheked Mixtape",
                "Crude tempest",
                "Daily days",
                "Don't feed the animals",
                "DRIVEKEY",
                "Elegant move",
                "freedom",
                "granpusler",
                "HA! gose the wheesel",
                "Hey light nerds",
                "It's a cord grove",
                "Laywire",
                "Nighty night",
                "NOW'S YOUR CHANSE TO MAKE",
                "Queen & Kings game board",
                "Rough & Tumble",
                "Sevilton",
                "the knight in fake armor",
                "The power of freedom",
                "The Prophecy",
                "The roxuls are being colored",
                "The royal kerfuffle",
                "True gamer",
                "TV Snow",
                "W A S D",
                "Wearking",
                "WELCOME TO PIECES & PARTS",
                "Wires all tangled up"
            ],
            "FNF": [
                "Har' the lost",
                "Main garden (inst)",
                "Main garden (vocals)",
                "Main garden",
                "Reo 2 BF Vocals",
                "Reo 2 Inst",
                "Reo 2 R Vocals",
                "Reo 2",
                "Tetra-fatigue (Inst)",
                "Tetra-fatigue (Vocals)",
                "Tetra-fatigue",
                "Обнадеживающий сад (Inst)",
                "Обнадеживающий сад (Vocals)",
                "Обнадеживающий сад"
            ],
            "Generic OST Album": [
                "Generic []",
                "Generic Ancient Ruins",
                "Generic Boss N-2",
                "Generic Boss",
                "Generic Dangerus Place",
                "Generic Desision",
                "Generic Ethnic Encounter",
                "Generic Field",
                "Generic Forest Village",
                "Generic Secret Boss N-2",
                "Generic Secret Boss",
                "Generic Snowy",
                "Generic Tension",
                "Generic Town"
            ]
        },
        "Mine": [
            "[OVERLOADED] [Deltarune Chapters combined] - Orchestral [Instrumental]",
            "[OVERLOADED] [Deltarune Chapters combined] - Orchestral",
            "·IN(K)TAKE· Trailer",
            "1K subs Tailer",
            "1K subs",
            "5-4-3-2-Down streat",
            "900 subs",
            "A single man's rehearsal",
            "A strugulling beginning",
            "A terrible joke + Big chaos [Deltarune Chapters combined] - Orchestral",
            "Apres cymical",
            "Band roll",
            "Bassoon tale",
            "Battle Trace",
            "BIG-BACKPAIN - Faynaly & CrystalFoxxie",
            "Blast-Model",
            "Brass Princess - Themes (Introduction + Bring the kingdom to glory + Hello once again)",
            "Buisness gone out of hand",
            "Bumping in",
            "Cannon winter",
            "Cluster cult",
            "Cold corner",
            "Complot Boolea-ttack",
            "Conclussion terms Ver. 2",
            "Conclussion terms",
            "Controversial wrath",
            "cronos center's cristal field",
            "danger classic",
            "daunting feeling",
            "Daylight kingdom diorama [Piano version]",
            "Daylight kingdom diorama",
            "Diest Grand",
            "Dim torches inside",
            "Distance",
            "distant glitter",
            "distorsion trumpet Orchestral Force",
            "DO Orchestral",
            "Doria Gloria",
            "Drag sorrow",
            "Draining your feelings",
            "Dwizzeldilalla Morning",
            "Epic BT",
            "ESMEGiMA But is a boss battle",
            "ESMEGiMA",
            "Exposing my diferent music",
            "Fay Naly Multi Cortes - Intro",
            "Fay-lament - in c major",
            "Fay-lament - in c minor",
            "FayNaly - Order of Honor",
            "Forgotten light",
            "Gradient disappearance. Piano Concerto No. 1",
            "Grain fog",
            "Half harm knight",
            "Harmonizing the simple chords Piano",
            "Harmonizing the simple chords",
            "Hollow hearts of war",
            "Home like palace - Faynaly & CrystalFoxxie",
            "I don't want to go...",
            "Imaginary concept",
            "Incoming machine",
            "Interest modeling",
            "Jester Card",
            "Joyful Experience",
            "just fast",
            "La Maquina Is Comming",
            "Last Hope",
            "Laywire & Wereking [Deltarune Chapters combined] - Orchestral",
            "Light cave",
            "Light course",
            "Long white and bule scarf",
            "Lullaby",
            "Mortal suspension",
            "Multivers Champions Theme",
            "Non confrontable",
            "November",
            "Now Streaming",
            "Offering to my sire",
            "Old castle",
            "Once on shot ver2",
            "Once on shot",
            "Open Field Battle",
            "Organ dance [Organ version]",
            "Organ dance",
            "Overture in 9 over 4",
            "Phase of wind",
            "Polygonal looks",
            "Portal rotion",
            "Provition of decay",
            "Pulverized army",
            "Q.round [Deltarune Chapters combined] - Orchestral",
            "Race+dead_lullaby",
            "Reolanex ver2",
            "Reolanex",
            "Reverse Injuries",
            "Right now i have no ideas sorry",
            "Roll cut",
            "Sadness Crypt",
            "Save me",
            "Save Yourself",
            "School",
            "Sentimental emphasis",
            "Sevilton themes [Deltarune Chapters combined] - Orchestral",
            "Sky grace",
            "slowfication orchestral",
            "Star knight",
            "Stars from the wind",
            "Storm wave",
            "Story needed battles [Deltarune Chapters combined] - Orchestral",
            "tabern",
            "Tale from sa king",
            "The adventure beneath the surface - Stray [fan made - conceptual music]",
            "The Beginning [Remake]",
            "the beginning",
            "the color of the sound",
            "The desert that's made out of crystal",
            "The holydays passing by",
            "The long window",
            "The machinist Ver. 2",
            "The machinist",
            "The new you",
            "The rise of the star blazer - MidnightMunchies",
            "The royal ars kicking [Deltarune Chapters combined] - Orchestral",
            "The shine of a new day strikes you with joy",
            "The stars in my sky",
            "The triumph on my tone",
            "Theories of the past",
            "Ther color - Sorta Force",
            "Time to time, i sleep",
            "Tired of crushed dreams",
            "Tragic re-encounter",
            "United at last",
            "Venus atmospher",
            "Wereking [Deltarune Chapters combined] - Orchestral",
            "Wet memories",
            "Yoserin pice - hard to belive 7&5 over 4",
            "Yoserin-K piano pice 1-b",
            "Yoserin-K piano pice",
            "yumme niki (orchestral room my take)",
            "Обнадеживающий сад",
            "Погоня"
        ]
    },
    "Cover Arrangements": [
        "A Sunny Day Is Watching Over You - Nekojishi",
        "Addict - Hazbin Hotel",
        "An Enigmatic Encounter - Undertale (Last breath) ver. 2",
        "An Enigmatic Encounter - Undertale (Last breath)",
        "Anarchy Rainbow - Splatoon 3 [Choir interpretation]",
        "Anarchy Rainbow - Splatoon 3 [Instrumental]",
        "Anarchy Rainbow - Splatoon 3 Ver. 2 [Choir interpretation]",
        "Anarchy Rainbow - Splatoon 3 Ver. 2 [Instrumental]",
        "Anarchy Rainbow - Splatoon 3 Ver. 2",
        "Anarchy Rainbow - Splatoon 3",
        "ANIMAL IN ME  - Solence",
        "ANIMAL IN ME - Solence Ver. 2",
        "Area Zero - Pokémon Scarlet & Violet Ver. 2",
        "Area Zero - Pokémon Scarlet & Violet",
        "Area Zero Wild Battle - Pokémon Scarlet & Violet",
        "Ashfaghma ot bantiem (Bergentrückung Arragment) - Undertale",
        "Attack of the Killer Queen Remix (Attack of the Killer Queen Arragment) - Deltarune",
        "Avast Your Ass - Kitsune²",
        "Backbone [Phase 3] - Disbelief Papyrus Ver. 2",
        "Backbone [Phase 3] - Disbelief Papyrus",
        "Bad Apple - Touhou project ",
        "Bad Apple - Touhou project ver. 2",
        "Balrog's Theme - Cave Story",
        "Battle (destruction) - Shin Megami Tensei V",
        "Battle (guardian) - TLOZ BOTW",
        "BATTLE AGAINST THE WORLD - Deltarune [Chapter Rewritten]",
        "BIG BANG - Deltarune [Chapter Rewritten]",
        "BIG BANG (Updated Version) - Deltarune [Chapter Rewritten]",
        "BITE [FERNAN MIX] [No FNF Vocals]",
        "BITE [FERNAN MIX]",
        "Bloody Tears - Castelvania",
        "Blooming revolver - Deltarune UST",
        "Blooming revolver (Orchestral arragment) - Deltarune UST",
        "Bonnqueet grand queen (Queen's themes Arragments) - Deltarune",
        "Boogieman [No FNF Vocals]",
        "Boogieman",
        "Bowser Road - MS64",
        "Calamari Inkantation 3MIX - Splatoon 3 [instrumental]",
        "Calamari Inkantation 3MIX - Splatoon 3",
        "Cascade - HomeStuck Vol 8",
        "Champion Battle - Pokemon Insurgence",
        "Clock Town Day 1 - TLOZ MM",
        "Coconut - Jayfoo [Doodley Soundtrack, Vol. 1]",
        "Colgera - TLOZ TOTK",
        "Cool, cool mountain - SM64",
        "Count What You Have Now - Mariya Takeuchi",
        "CP Violation - Half Life 2",
        "CREATIVE FREEDOM - U.Z Inu",
        "Credits song for my death - vivivivivi Ver. 2",
        "Credits song for my death - vivivivivi",
        "Daisy bell (Bicycle build for two) - Harry Dacre",
        "Darkest Lord - Miitopia ver. 2",
        "Darkest Lord - Miitopia",
        "Darkness Falls & Faint Courage - Deltarune",
        "Daycare - FNAF SB",
        "Deal Gone Wrong (violin fading) - Deltarune",
        "Deal Gone Wrong choir catastrhopy (Deal gone wrong Arragment) - Deltarune",
        "Deerclops (The E.F.S. of Winter) - Terraria",
        "Delete this tweet - Trash cans - Kevin Temmer",
        "Demon castle dracula - Super Castlevania IV",
        "Dialga's Fight to the Finish! - Pokemon Mystery Dungeon Explorers of Time Darkness",
        "Dire Dire Docks - MS64",
        "Dire Dire Docks - SM64 Ver. 2",
        "Discord - Eurobeat Ver 2",
        "Discord - Eurobeat",
        "Dj music man - FNAF SB",
        "Don't Ever Forget - Pokemon Mystery Dungeon (Explorers of Sky)",
        "Dracula's Keep - Super Castlevania IV",
        "Dracula's theme - Castelvania 4",
        "Driftveil city - Pokemon Black & White",
        "Duel of the Fates - StarWars",
        "Echo [Gumi Ingles] - Crusher-P",
        "Ei Mori Roujke - Nonesuch (Bulgarian female choir)",
        "Even in Death - Homestuck Vol 7",
        "Final chance [Phase 4] - Disbelief Papyrus",
        "Finding another medium (another medium Arragment) - Undertale",
        "Flowering Night - Touhou Project",
        "Forgotten One Nyx - Pokémon Insurgence",
        "From the Shadows - Shovel Knight",
        "Gang-Plank Galleon - Super Smash Bros. Ultimate",
        "Gerudo Valley - TLOZ OOT ver. 2",
        "Gerudo Valley - TLOZ OOT",
        "Giants - Skylander Giants",
        "GIGA プリン - Deltarune [The Other Puppet] Ver. 2",
        "GIGA プリン - Deltarune [The Other Puppet]",
        "God Save The Queen - UK",
        "Goodbye To A World - Poter Robinson",
        "Gourmet Race - Kirby Super star",
        "GRAND ILLUSsSIONSsS - Deltarune Chapter 3 UST",
        "Grass Skirt Chase - SpongeBob SquarePants",
        "Happy Birthday",
        "HARD DRIVE - Griffinilla [Instrumental]",
        "HARD DRIVE - Griffinilla",
        "Heartaches - Al-Bowlly",
        "Heaven Says - Deltarune UST Ver. 2",
        "Heaven Says - Deltarune UST",
        "Hell March 3 - Red Alert 3",
        "Hijo de la luna - Mecano ver. 2",
        "Hijo de la luna - Mecano",
        "His World (Sonic's Theme) - Sonic the Hedgehog [Instrumental]",
        "His World (Sonic's Theme) - Sonic the Hedgehog",
        "Horse racing - Chen jun ver.2 ",
        "Horse racing - Chen jun",
        "I CAN Y̴̘͘O̶U ̴̛̲̓C̶̭͒̿Ḁ̷̖̒N̵̻̽̊ - Deltarune [Chapter Rewritten]",
        "Idol - YOASOBI Ver.2 [Instrumental]",
        "Idol - YOASOBI Ver.2",
        "Idol - YOASOBI",
        "Inferno - Fire Force",
        "Interstellar Retribution [Phase 1] - Disbelief Papyrus Ver. 2",
        "Interstellar Retribution [Phase 1] - Disbelief Papyrus",
        "It's been so long - The living tombstone [FNAF]",
        "I've Had Enough of You - Billie Bust Up [Instrumental]",
        "I've Had Enough of You - Billie Bust Up",
        "Jedi Temple March - StarWars",
        "Jinora's light (Lotus Despair) - Legend of Korra",
        "Just look my way - Helluva Boss [Instrumental]",
        "Just look my way - Helluva Boss",
        "Just the two of us - Grover Washington, Jr. (feat. Bill Withers)",
        "Kaboomberg - ToonTown Ver. 2",
        "Kaboomberg - ToonTown",
        "Kalos Region - Pokemon X & Y",
        "Killer Kueen Bites The Dust - Deltarune [Chapter Rewritten]",
        "KING (Gumi) - Kanaria [Instrumental]",
        "KING (Gumi) - Kanaria",
        "Kokiri Forest - TLOZ OOT",
        "La Gozadera - Gente de Zona (ft. Marc Anthony) Instrumental",
        "La Gozadera - Gente de Zona (ft. Marc Anthony)",
        "Lagtrain - 稲葉曇 [Instrumental]",
        "Lagtrain - 稲葉曇",
        "Laugh Track - Deltarune Chapter 3 UST ver. 2",
        "Laugh Track - Deltarune Chapter 3 UST",
        "Lavender Town - Pokemon Red, Blue, Green & Yellow",
        "Law - Shin Megami Tensei III Nocturne",
        "Left Unchecked [No FNF Vocals]",
        "Left Unchecked",
        "Library Piano - Luigi's Mansion Dark Moon",
        "Littleroot Town - Pokemon Ruby & Sapphire & Emerald",
        "Lorule Castle - TLOZ ALBW ver. 2",
        "Lorule Castle - TLOZ ALBW",
        "Lost Woods - TLOZ OOT",
        "Lost, forgotten, down Friend (Lost girl - arragment) - Deltarune",
        "Louane - JOUR 1",
        "Low Kromer (Big Shot Arragment) - Deltarune",
        "Main theme - Bad Piggies ver. 2",
        "Main theme - Bad Piggies",
        "Main theme - El Vendedor de Humo - The Smoke Seller (Recreation & Cover)",
        "Main theme - Papers Please",
        "Main Theme - Skylanders SuperChargers",
        "Main Theme - Skylanders The Swap Force",
        "Main Theme - Terminator Genisys",
        "Main theme - Wii Sports",
        "Marble Machine - Wintergatan",
        "Marx's Theme - Kirby Super star",
        "Megalo Clamour - Kibo",
        "Megalo Strike Back - Earthbound Halloween hack",
        "Megalo strikes back [Phase 2] - Disbelief Papyrus Ver. 2",
        "Megalo strikes back [Phase 2] - Disbelief Papyrus",
        "Merry Go Round Life - howl's castle ver. 2",
        "Merry Go Round Life - howl's castle",
        "Merry Go Round Super - SM64",
        "Metatron - Shin Megami Tensei III Nocturne",
        "Missa langosta - Missa sinfonia",
        "MonoChrome [No FNF Vocals]",
        "MonoChrome",
        "MTC - S3RL",
        "Never gonna give you up - Rick Astley",
        "Nigh of nights - Touhou project",
        "Nightmare Knight - Cucumber quest (Toby fox) Ver. 2 ",
        "Nightmare Knight - Cucumber quest (Toby fox)",
        "No More Deals - Undetale (No More Deals) ver. 2",
        "No More Deals - Undetale (No More Deals)",
        "No se habla de bruno - Encanto",
        "OFFICIAL WAY - Deltarune Chapter 3 UST",
        "Open up your eyes - My little pony (The Movie) [Instrumental]",
        "Open up your eyes - My little pony (The Movie)",
        "Opposing Bloodlines - Castlevania 64",
        "PEACHES - [Jack Black - BOWSER] The super mario movie [inst]",
        "PEACHES - [Jack Black - BOWSER] The super mario movie",
        "Perseverance - Gris",
        "Phantasm [No FNF Vocals]",
        "Phantasm",
        "Piranha Plants on Parade - Super Mario Wonder",
        "Pirate seas - PVZ2",
        "Pirates sea [unused track] - PVZ2",
        "PokeWalker - Pokemon Heart Gold & Soul Silver",
        "PS5 - MrMoMMusic (feat. Alan Walker)",
        "Push Your Limits - Brian Michael Hinds [Instrumental]",
        "Push Your Limits - Brian Michael Hinds",
        "Relight [Gaster's theme] - Underverse",
        "Road Less Taken Real - Persona Q2",
        "Rolling Down the Street - Fearofdark",
        "Rolling Girl - Wowaka ver.2",
        "Rolling Girl - Wowaka",
        "Savior of the Waking World - Homestuck Vol 5",
        "Schoolhouse Trouble! - Baldi's Basics Classic Remastered",
        "Shala's Theme - Dream Devourer [Anti-Remix]",
        "Sidon's theme - TLOZ BOTW",
        "Silly Billy [Inst]",
        "Silly Billy [No FNF Vocals]",
        "Silly Billy",
        "Sis Puella Magica - Puella Magi Madoka Magica",
        "Slider - SM64",
        "Somebody else - Kevin Temmer",
        "Song of Storms - TLOZ OOF",
        "Spooky scary skeletons - Andrew Gold [Happy halloween]",
        "Spooky scary skeletons - Andrew Gold",
        "Spyro's Adventure - Skylanders",
        "Staff Rol - SM64",
        "Stay With Me - Miki Matsubara [instrumental]",
        "Stay With Me - Miki Matsubara",
        "Stolas Sings - Helluva Boss",
        "Stolas Sings [Dark] - Helluva Boss",
        "Stolas Singss - Helluva Boss [Instrumental]",
        "Stolas Singss [Dark] - Helluva Boss [Instrumental]",
        "Strike the earth - Shovel Knight",
        "Super Idol - 105",
        "Sweden Minecraft",
        "The Boiler - ToonTown Rewritten",
        "The Crisis of Red and Green - Mario & Luigi [Partners in Time]",
        "The Grand Finale - Mario & Luigi Bowser inside story",
        "The Great Sage's - Miitopia",
        "The Killer Spin - Deltarune UST",
        "The Killer Spin (Orchestral arragment) - Deltarune UST",
        "The Minister (Vision Crew's) - Deltarune Chapter 5 UST",
        "The Nowhere King - Centaurworld [Instrumental]",
        "The Nowhere King - Centaurworld",
        "The Opening of Every Animated Film - Kevin Temmer Tunes",
        "The Piano Duet - Corpse Bride",
        "The slaughter continues - Undertale (Last breath)",
        "The Toybox - Stupendium",
        "The World Revolving Another remix (The World Revolving - Arragment) - Deltarune",
        "Tower Battle - Pokemon shield & Sword",
        "Triple Trouble [No FNF Vocals] Ver. 2",
        "Triple Trouble [No FNF Vocals]",
        "Triple Trouble Ver. 2",
        "Triple Trouble",
        "U.N. Owen was her - Touhou Project",
        "Ultimate Bowser - MS64",
        "Upward Movement (Dave Own) - HomeStuck Vol 2",
        "Vitality - Helltaker",
        "Wart - Super Mario Bros 2 [Extended]",
        "Wart - Super Mario Bros 2",
        "We are - One Pice",
        "We Dont Talk About Bruno - Encanto",
        "We Dont Talk About Bruno No Se Habla De Bruno - Encanto [Instrumental]",
        "Wet Hands - Minecraft",
        "Wielder Volo Battle - Pokemon Arceus ver. 2",
        "Wielder Volo Battle - Pokemon Arceus",
        "wild battle - Pokemon Ruby & Sapphire & Emerald",
        "Yap Squad [Inst]",
        "Yap Squad [No FNF Vocals]",
        "Yap Squad",
        "Yo buddy - Deltarune [The Other Puppet]",
        "You smell of death flowers - Vslush",
        "You Will Be Ok - Helluva Boss",
        "You'er Truly A Real Boy! - Deltarune [fan UST]",
        "Your Contract Has Expired - A Hat In Time Ver. 2",
        "Your Contract Has Expired - A Hat In Time",
        "Your Contract Has Expired {hard} - A Hat In Time Ver. 2",
        "Your Contract Has Expired {hard} - A Hat In Time",
        "YOUR LAST GIFT - Local H00ligan",
        "Zero Two - Kirby 64 (The Crystal Shards)",
        "柴又 (Shibamata) - Dot nigou"
    ],
    "Cover Albums": {
        "(OLD) Deltarune Chapter 1": [
            "-.Char Joined",
            "-.Man",
            "-.Thrash Rating",
            "01.ANOTHER HIM",
            "02.Beginning",
            "03.School",
            "04.Susie",
            "05.The Door",
            "06.Cliffs",
            "07.The Chase",
            "08.The Legend",
            "09.Lancer ver. 2",
            "09.Lancer",
            "10.Rude buster",
            "11.Empty Town",
            "13.Field of Hopes and Dreams ver. 2",
            "13.Field of Hopes and Dreams",
            "14.Fanfare (from Rose of Winter) short",
            "14.FanFare (from Rose of Winter)",
            "15.Lantern",
            "16.I'm very bad",
            "17.Chekers Dance",
            "18.Quiet Autumn",
            "19.Scarlet Forest",
            "20.Thrash Machine",
            "21.VS. Lancer",
            "22.Basement",
            "23.Imminent Death",
            "24.VS. Susie",
            "25.Card Castle",
            "26.Rouxls Kaard-Ruruskado",
            "27.April 2012",
            "28.Hip shop",
            "29.Gallery",
            "30.Chaos King ver. 2",
            "30.Chaos King",
            "31.Darkness Falls",
            "32.The Circus",
            "33.The World Revolving ver. 2",
            "33.The World Revolving",
            "34.Friendship",
            "35.THE HOLY",
            "36.Your Power",
            "37.A Town Called Hometown",
            "38.You Can Always Come Home",
            "39.Don't Forget",
            "40.Before the Story -482005294-",
            "40.Before the Story",
            "42.sans."
        ],
        "(OLD) Deltarune Chapter 2": [
            "-.A-pplause for Berdly",
            "-.Berdly Battle (Really Tense Heartbeat Momento Version)",
            "-.Cyber Battle",
            "-.Cybercity (Alt)",
            "-.D.ogg ",
            "01.Faint Glow",
            "02.Girl Next Door",
            "03.My Castle Town Ver. 2",
            "03.My Castle Town",
            "05.Queen Ver. 2",
            "05.Queen Ver. 3",
            "05.Queen",
            "06.A Cybers World Ver. 2",
            "06.A Cybers World",
            "07.A Simple Diversion ver. 2",
            "07.A Simple Diversion",
            "08.Almost To The Guys! Ver. 2",
            "08.Almost To The Guys!",
            "10.When I Get Mad I Dance Like This",
            "11.Toby Fox & Lena Raine - Cyber Battle",
            "12.When I Get Happy I Dance Like This",
            "13.Sound Studio",
            "14.Berdly",
            "15.Smart Race ver. 2",
            "15.Smart Race",
            "16.Faint Courage (Game Over) Ver. 2",
            "16.Faint Courage (Game Over) Ver. 3",
            "16.Faint Courage (Game Over)",
            "16.Faint Courage (Game Over)B side",
            "17.WELCOME TO THE CITY",
            "18.Mini Studio",
            "19.Holyday Studio",
            "20.Cool Mixtape",
            "21.HEY EVERY!",
            "22.Spamtom",
            "23.NOW'S YOUR CHANCE TO BE A",
            "24.Elegant Entrance",
            "25.Bluebird of Misfortune PIANO & VIOLIN",
            "25.Bluebird of Misfortune",
            "26.Pandora Palace Ver. 2",
            "26.Pandora Palace",
            "27.KEYGEN",
            "28.Acid Tunnel of Love",
            "29.It's Pronounced ¡Rules! ver. 2",
            "29.It's Pronounced ¡Rules!",
            "30.Lost Girl",
            "31.Ferris Wheel",
            "32.Toby Fox & Lena Raine & Marcy Nabors - Attack of the Killer Queen",
            "33.Giga Size",
            "34.Powers Combined",
            "35.Knock You Down",
            "36.The Dark Truth Ver. 2",
            "36.The Dark Truth",
            "37.Digital Roots",
            "38.Deal Gone Wrong ver. 2",
            "38.Deal Gone Wrong",
            "39.Big Shot ver. 2",
            "39.Big Shot ver. 3",
            "39.Big Shot",
            "40.A Real Boy!",
            "41.Dialtone",
            "42.sans.",
            "43.Napsta Alarm",
            "45.Until next time ver. 2",
            "45.Until next time"
        ],
        "(OLD) FNF Vs. Retrospecter": [
            "Acidiron [No FNF Vocals]",
            "Acidiron",
            "Fuzzy Feeling [No FNF Vocals]",
            "Fuzzy Feeling",
            "HeartMelter [no fnf voice]",
            "HeartMelter",
            "Overtime [no fnf voice]",
            "Overtime",
            "Preppy [no fnf voice]",
            "Preppy",
            "Preseason [no fnf voice]",
            "Preseason",
            "Retro [no fnf voice]",
            "Retro",
            "Satisfracture [no fnf voice]",
            "Satisfracture",
            "Sigma [no fnf voice]",
            "Sigma",
            "Spectral [no fnf voice]",
            "Spectral"
        ],
        "(OLD) Undertale": [
            "-.Absolutely Overfamiliar Shrine",
            "-.Before the Story -482005294-",
            "-.Before the Story",
            "-.Dance of dog",
            "-.Dog casino",
            "-.King Description",
            "-.Mad Mew Mew",
            "-.Mysterious Shrine",
            "+.mus_st_him",
            "001.Once Upon a Time",
            "002.Start Menu",
            "003.Your Best Friend",
            "004.Fallen Down Ver. 2",
            "004.Fallen Down",
            "005.Ruins Ver. 2",
            "005.Ruins",
            "006.Uwa!! So Temperate",
            "007.Anticipation",
            "008.Unnecessary Tension",
            "009.Enemy Approaching",
            "010.Ghost Fight",
            "011.Determination Ver. 2",
            "011.Determination",
            "012.Home",
            "013.Home (Music Box)",
            "014.Heartache Ver. 2",
            "014.Heartache",
            "015.sans.",
            "016.Nye heh heh! Ver. 2",
            "016.Nye heh heh!",
            "017.Snowy",
            "018.Uwa So Holiday",
            "020.Mysterious Place",
            "021.Dog Song",
            "022.Snowdin Town",
            "023.Shop Ver. 2",
            "023.Shop",
            "024.Bonetrousle Ver. 2",
            "024.Bonetrousle",
            "025.Dating Start",
            "026.Dating Tense!",
            "027.Dating Fight!",
            "028.Premonition",
            "029.Danger Mystery",
            "030.Undyne",
            "031.Waterfall",
            "032.Run!",
            "033.Quiet Water",
            "034.Memory",
            "035.Bird That Carries You Over A Disproportionately Small Gap ver. 2",
            "035.Bird That Carries You Over A Disproportionately Small Gap",
            "036.Dummy!",
            "037.Pathetic House",
            "038.Spooktune",
            "039.Spookwave",
            "040.Ghouliday",
            "041.Chill",
            "042.Thundersnail",
            "043.Temmie Village ver. 2",
            "043.Temmie Village",
            "044.Tem Shop",
            "045.NGAHHH!!",
            "046.Spear of Justice",
            "047.Ooo",
            "048.Alphys",
            "049.It's Showtime",
            "050.Another Medium ver. 2",
            "050.Another Medium",
            "051.Metal Crusher",
            "052.Uwa!! So HEATS!!",
            "053.Hotel Ver. 2",
            "053.Hotel",
            "054.Stronger Monsters",
            "055.Can You Really Call This A Hotel I Didn't Recieve A Mint On My Pillow Or Anything",
            "056.Confession",
            "057.Live Report",
            "058.Death Report ver.2",
            "058.Death Report",
            "059.Spider Dance",
            "060.Wrong Enemy",
            "061.Oh! One True Love",
            "062.Oh! Dungeon",
            "063.It's Raining Somewhere Else",
            "064.CORE Approach",
            "065.CORE",
            "066.Last Episode",
            "067.Oh My",
            "068.Death by Glamour ver. 2",
            "068.Death by Glamour",
            "069.For the Fans",
            "071.Undertale ver. 2",
            "071.Undertale",
            "072.Song That Might Play When You Fight Sans",
            "074.Small Shock",
            "076.Bergentrückung Ver. 2",
            "076.Bergentrückung",
            "077.ASGORE ver. 2",
            "077.ASGORE",
            "078.You Idiot",
            "079.Your Best Nightmare ver. 2",
            "079.Your Best Nightmare",
            "080.Finale",
            "081.An Ending",
            "082.She's Playing Piano",
            "083.Here We Are",
            "084.Amalgam ver. 2",
            "084.Amalgam",
            "085.Fallen Down (Reprise) ver. 2",
            "085.Fallen Down (Reprise)",
            "086.Don't Give Up",
            "087.Hopes and Dreams ver. 2",
            "087.Hopes and Dreams",
            "088.Burn in Despair",
            "089.SAVE the WORLD Ver. 2",
            "089.SAVE the WORLD",
            "090.His Theme",
            "092.Reunited ver. 2",
            "092.Reunited",
            "093.Start Menu (full)",
            "094.Respite",
            "095.Bring It In Guys Ver. 2",
            "095.Bring It In Guys",
            "096.Last Goodbye Ver. 2",
            "096.Last Goodbye",
            "097.But the Earth Refused to Die ver. 2",
            "097.But the Earth Refused to Die",
            "098.Battle Against a True Hero Ver. 2",
            "098.Battle Against a True Hero Ver. 3",
            "098.Battle Against a True Hero",
            "099.Power of NEO",
            "100.MEGALOVANIA Ver. 2",
            "100.MEGALOVANIA",
            "101.Good Night"
        ],
        "Dungeons of Aether": [
            "007.First Quarry (Area 1)",
            "008.Ground Breakers (Battle 1)"
        ],
        "FNF Smoke 'Em Out Struggle": [
            "Fading",
            "Headache",
            "Nerves",
            "Release"
        ],
        "FNF Vs. witthy": [
            "Ballistic",
            "Ballistic[No FNF Vocals]",
            "Lo-Fight [No FNF Vocals]",
            "Lo-Fight",
            "Low Rise [No FNF Vocals]",
            "Low Rise",
            "Overhead",
            "Underground"
        ],
        "Undertale": [
            "-.Absolutely Overfamiliar Shrine",
            "-.Before the Story",
            "-.Dance of dog",
            "-.Dog casino",
            "-.King Description",
            "-.Mad Mew Mew",
            "-.Mysterious Shrine",
            "-.Sigh of Dog",
            "-.Star",
            "-.The Wrong Number Song",
            "-.Toby Room",
            "001.Once Upon a Time",
            "002.Start Menu",
            "003.Your Best Friend",
            "004.Fallen Down",
            "005.Ruins",
            "006.Uwa!! So Temperate",
            "007.Anticipation",
            "008.Unnecessary Tension",
            "009.Enemy Approaching",
            "010.Ghost Fight",
            "011.Determination",
            "012.Home",
            "013.Home (Music Box)",
            "014.Heartache",
            "015.sans.",
            "016.Nye heh heh!",
            "017.Snowy",
            "018.Uwa So Holiday",
            "019.Dogbass",
            "020.Mysterious Place",
            "021.Dog Song",
            "022.Snowdin Town",
            "023.Shop",
            "024.Bonetrousle",
            "025.Dating Start",
            "026.Dating Tense!",
            "027.Dating Fight!",
            "028.Premonition",
            "029.Danger Mystery",
            "030.Undyne",
            "031.Waterfall",
            "032.Run!",
            "033.Quiet Water",
            "034.Memory",
            "035.Bird That Carries You Over A Disproportionately Small Gap",
            "036.Dummy!",
            "037.Pathetic House",
            "038.Spooktune",
            "039.Spookwave",
            "040.Ghouliday",
            "041.Chill",
            "042.Thundersnail",
            "043.Temmie Village",
            "044.Tem Shop",
            "045.NGAHHH!!",
            "046.Spear of Justice",
            "047.Ooo",
            "048.Alphys",
            "049.It's Showtime",
            "050.Metal Crusher",
            "051.Another Medium",
            "052.Uwa!! So HEATS!!",
            "053.Stronger Monsters",
            "054.Hotel",
            "055.Can You Really Call This A Hotel I Didn't Receive A Mint On My Pillow Or Anything",
            "056.Confession",
            "057.Live Report",
            "058.Death Report",
            "059.Spider Dance",
            "060.Wrong Enemy",
            "061.Oh! One True Love",
            "062.Oh! Dungeon",
            "063.It's Raining Somewhere Else",
            "064.CORE Approach",
            "065.CORE",
            "066.Last Episode",
            "067.Oh My...",
            "068.Death by Glamour",
            "069.For the Fans",
            "071.Undertale",
            "072.Song That Might Play When You Fight Sans",
            "074.Small Shock",
            "076.Bergentrückung",
            "077.ASGORE",
            "078.You Idiot",
            "079.Your Best Nightmare",
            "080.Finale",
            "081.An Ending",
            "082.She's Playing Piano",
            "083.Here We Are",
            "084.Amalgam",
            "085.Fallen Down (Reprise)",
            "086.Don't Give Up",
            "087.Hopes and Dreams",
            "088.Burn in Despair",
            "089.SAVE the WORLD",
            "090.His Theme",
            "092.Reunited",
            "093.Start Menu (full)",
            "094.Respite",
            "095.Bring It In Guys",
            "096.Last Goodbye",
            "097.But the Earth Refused to Die",
            "098.Battle Against a True Hero",
            "099.Power of NEO",
            "100.MEGALOVANIA",
            "101.Good Night",
            "A-10.Abandoned Town",
            "A-10.Dog Hole",
            "A-10.Memory (10 Years Later)",
            "A-10.Pseudo Legendary Tree",
            "A-10.School",
            "A-10.Snowdrift",
            "A-10.Snowed Inn Jazz",
            "A-10.Song That Plays When Somebody Verses Sans",
            "A-10.Strongerer Monsters",
            "A-10.Ultranap",
            "A-10.Underwater Town",
            "A-10.what's up",
            "A-10.Wrong Number Remix",
            "Sound test.Gaster's theme",
            "Sound test.Happy Town",
            "Sound test.Meat Factory",
            "Sound test.Trouble Dingle"
        ]
    },
    "Memes": [
        "among us remix (my cumbia)",
        "Cool Remix extended",
        "Cool Remix",
        "Main theme - Wii Sports (Minor key)",
        "PS5 [Fortnite Battle Pass] - MrMoMMusic (feat. Alan Walker)",
        "Smash Susie"
    ]
}